COMMENT ON COLUMN TMP_MEGOKR_API.SN                               IS '일련번호';
COMMENT ON COLUMN TMP_MEGOKR_API.JOSACODE                         IS '조사코드';
COMMENT ON COLUMN TMP_MEGOKR_API.QLTWTR_INSPCT_SN                 IS '수질검사일련번호';
COMMENT ON COLUMN TMP_MEGOKR_API.GENNUM                           IS '관정일련번호';
COMMENT ON COLUMN TMP_MEGOKR_API.INVSTG_YEAR                      IS '조사연도';
COMMENT ON COLUMN TMP_MEGOKR_API.ODR                              IS '순번';
COMMENT ON COLUMN TMP_MEGOKR_API.DPH_CL_CODE                      IS '심도분류코드';
COMMENT ON COLUMN TMP_MEGOKR_API.DPH_VALUE                        IS '심도값';
COMMENT ON COLUMN TMP_MEGOKR_API.WATSMP_DE                        IS '채수일자';
COMMENT ON COLUMN TMP_MEGOKR_API.QLTWTR_INSPCT_DE                 IS '수질검사일자';
COMMENT ON COLUMN TMP_MEGOKR_API.DTA_INPUT_DE                     IS '자료입력일자';
COMMENT ON COLUMN TMP_MEGOKR_API.DCSN_DE                          IS '확정일자';
COMMENT ON COLUMN TMP_MEGOKR_API.FRST_REGIST_DT                   IS '최초등록일시';
COMMENT ON COLUMN TMP_MEGOKR_API.LAST_CHANGE_DT                   IS '최종변경일시';
COMMENT ON COLUMN TMP_MEGOKR_API.UGRWTR_PRPOS_CODE                IS '지하수용도코드';
COMMENT ON COLUMN TMP_MEGOKR_API.DRNK_AT                          IS '음용여부';
COMMENT ON COLUMN TMP_MEGOKR_API.UGRWTR_WQN_INPUT_INSTT_CODE      IS '지하수수질입력기관코드';
COMMENT ON COLUMN TMP_MEGOKR_API.QLTWTR_INSPCT_IMPRTY_RESN_CTNT   IS '수질검사불가사유내용';
COMMENT ON COLUMN TMP_MEGOKR_API.BRTC_NM                          IS '시도명';
COMMENT ON COLUMN TMP_MEGOKR_API.SIGUN_NM                         IS '시군구명';
COMMENT ON COLUMN TMP_MEGOKR_API.EMD_NM                           IS '읍면동명';
COMMENT ON COLUMN TMP_MEGOKR_API.LI_NM                            IS '리명';
COMMENT ON COLUMN TMP_MEGOKR_API.ADDR                             IS '주소';
COMMENT ON COLUMN TMP_MEGOKR_API.PUBWELL_AT                       IS '공공관정여부';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_TOT_COL_CNTS                  IS '수질항목 WT_TOT_COL_CNTS (일반세균수)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_TOT_CLF                       IS '수질항목 WT_TOT_CLF (총대장균군)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_FCL_CFS                       IS '수질항목 WT_FCL_CFS (분원성대장균군)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_ESC_COL                       IS '수질항목 WT_ESC_COL (대장균)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_PLB                           IS '수질항목 WT_PLB (납)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_FLR                           IS '수질항목 WT_FLR (불소)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_ASN                           IS '수질항목 WT_ASN (비소)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_SLN                           IS '수질항목 WT_SLN (셀레늄)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_HDG                           IS '수질항목 WT_HDG (수소이온농도)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_CYA                           IS '수질항목 WT_CYA (시안)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_AMN_NTG                       IS '수질항목 WT_AMN_NTG (암모니아성질소)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_NTR_NTG                       IS '수질항목 WT_NTR_NTG (질산성질소)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_CDM                           IS '수질항목 WT_CDM (카드뮴)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_BOR                           IS '수질항목 WT_BOR (붕소)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_CHR                           IS '수질항목 WT_CHR (크롬)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_PEN                           IS '수질항목 WT_PEN';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_DZN                           IS '수질항목 WT_DZN';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_PRT                           IS '수질항목 WT_PRT';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_FNT                           IS '수질항목 WT_FNT';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_CBR                           IS '수질항목 WT_CBR';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_111_TCE                       IS '수질항목 WT_111_TCE';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_PCE                           IS '수질항목 WT_PCE';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_TCE                           IS '수질항목 WT_TCE';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_DCM                           IS '수질항목 WT_DCM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_BEZ                           IS '수질항목 WT_BEZ';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_TLE                           IS '수질항목 WT_TLE';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_EBZ                           IS '수질항목 WT_EBZ';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_CSL                           IS '수질항목 WT_CSL';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_011_DRE                       IS '수질항목 WT_011_DRE';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_CTC                           IS '수질항목 WT_CTC';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_012_DBR_003_CRP               IS '수질항목 WT_012_DBR_003_CRP';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_014_DOX                       IS '수질항목 WT_014_DOX';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_HDN                           IS '수질항목 WT_HDN (경도)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_PPC                           IS '수질항목 WT_PPC';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_SML                           IS '수질항목 WT_SML';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_FEV                           IS '수질항목 WT_FEV';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_COP                           IS '수질항목 WT_COP (구리)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_CMC                           IS '수질항목 WT_CMC';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_DTG                           IS '수질항목 WT_DTG';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_HID                           IS '수질항목 WT_HID';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_ZIC                           IS '수질항목 WT_ZIC';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_CRI                           IS '수질항목 WT_CRI';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_EVR                           IS '수질항목 WT_EVR';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_STE                           IS '수질항목 WT_STE';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_MGN                           IS '수질항목 WT_MGN';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_TBD                           IS '수질항목 WT_TBD (탁도)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_SAI                           IS '수질항목 WT_SAI';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_ALM                           IS '수질항목 WT_ALM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_ECD                           IS '수질항목 WT_ECD (전기전도도)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_OGP                           IS '수질항목 WT_OGP';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_006_CHR                       IS '수질항목 WT_006_CHR';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_HID_LBT                       IS '수질항목 WT_HID_LBT';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_TDS                           IS '수질항목 WT_TDS';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_DSO                           IS '수질항목 WT_DSO';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_ORP                           IS '수질항목 WT_ORP';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_EHC                           IS '수질항목 WT_EHC';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_TRT                           IS '수질항목 WT_TRT';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_NTR                           IS '수질항목 WT_NTR';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_KAL                           IS '수질항목 WT_KAL';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_CAL                           IS '수질항목 WT_CAL (칼슘)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_MGS                           IS '수질항목 WT_MGS (마그네슘)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_CLR                           IS '수질항목 WT_CLR (색도)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_BBN                           IS '수질항목 WT_BBN';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_CAI                           IS '수질항목 WT_CAI';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_NTI                           IS '수질항목 WT_NTI';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_SNT                           IS '수질항목 WT_SNT';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_BRM                           IS '수질항목 WT_BRM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_BRU                           IS '수질항목 WT_BRU';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_ATM                           IS '수질항목 WT_ATM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_SLC                           IS '수질항목 WT_SLC';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_LTU                           IS '수질항목 WT_LTU';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_MBD                           IS '수질항목 WT_MBD';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_VND                           IS '수질항목 WT_VND';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_GMN                           IS '수질항목 WT_GMN';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_CPE                           IS '수질항목 WT_CPE';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_NKE                           IS '수질항목 WT_NKE';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_EPN                           IS '수질항목 WT_EPN';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_PTA                           IS '수질항목 WT_PTA';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_MST                           IS '수질항목 WT_MST';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_CRF                           IS '수질항목 WT_CRF';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_012_DRE                       IS '수질항목 WT_012_DRE';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_TOC                           IS '수질항목 WT_TOC (총유기탄소)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_BTR                           IS '수질항목 WT_BTR';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_MBE                           IS '수질항목 WT_MBE';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_SSC                           IS '수질항목 WT_SSC';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_SDM                           IS '수질항목 WT_SDM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_SMN                           IS '수질항목 WT_SMN';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_SGL                           IS '수질항목 WT_SGL';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_AHP                           IS '수질항목 WT_AHP';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_YNE                           IS '수질항목 WT_YNE';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_NTN                           IS '수질항목 WT_NTN';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_COI                           IS '수질항목 WT_COI';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_CPM                           IS '수질항목 WT_CPM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_CTM                           IS '수질항목 WT_CTM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_012_DCM                       IS '수질항목 WT_012_DCM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_MTB                           IS '수질항목 WT_MTB';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_ZCM                           IS '수질항목 WT_ZCM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_MGM                           IS '수질항목 WT_MGM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_MBM                           IS '수질항목 WT_MBM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_STM                           IS '수질항목 WT_STM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_BAM                           IS '수질항목 WT_BAM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_BSM                           IS '수질항목 WT_BSM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_ANM                           IS '수질항목 WT_ANM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_NNM                           IS '수질항목 WT_NNM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_FRM                           IS '수질항목 WT_FRM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_TCL                           IS '수질항목 WT_TCL';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_TCM                           IS '수질항목 WT_TCM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_MTM                           IS '수질항목 WT_MTM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_THM                           IS '수질항목 WT_THM';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_OPS                           IS '수질항목 WT_OPS';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_DRO                           IS '수질항목 WT_DRO';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_GRC                           IS '수질항목 WT_GRC';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_CBT                           IS '수질항목 WT_CBT';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_CBD                           IS '수질항목 WT_CBD';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_PSP                           IS '수질항목 WT_PSP';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_AMN                           IS '수질항목 WT_AMN';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_HGS                           IS '수질항목 WT_HGS';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_SCD                           IS '수질항목 WT_SCD';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_AMI                           IS '수질항목 WT_AMI';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_TBC                           IS '수질항목 WT_TBC';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_URN                           IS '수질항목 WT_URN (우라늄)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_RDN                           IS '수질항목 WT_RDN (라돈)';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_FAP                           IS '수질항목 WT_FAP';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_NAI                           IS '수질항목 WT_NAI';
COMMENT ON COLUMN TMP_MEGOKR_API.WT_WTL                           IS '수질항목 WT_WTL';