-- ============================================================
-- TM_GD111010 (이용량시설) 컬럼 추가
-- 현재: BRNCH_ID, TELNO, EXECUTION_ID, SOURCE_REFS (4컬럼)
-- 추가: 표준화 자료 기준 65컬럼 (총 69컬럼)
-- 실행: docker exec -i gims_orchestrator_inner_oracle sqlplus k1m/1111@//localhost:1521/XEPDB1 < scripts/ddl/internal-oracle/alter-gd111010-facility.sql
-- ============================================================

ALTER TABLE TM_GD111010 ADD (
    INSTL_PSBLTY_FMT_CN     VARCHAR2(4000),
    GRNDS_GWEL_NO            VARCHAR2(50),
    EXMN_YMD                 VARCHAR2(8),
    EXMNR_NM                 VARCHAR2(30),
    CTPV_NM                  VARCHAR2(40),
    SGG_NM                   VARCHAR2(40),
    EMD_NM                   VARCHAR2(30),
    LI_NM                    VARCHAR2(40),
    BNJ                      VARCHAR2(20),
    GRNDS_BNJ_CN             VARCHAR2(100),
    ARND_LOTNO_CN            VARCHAR2(100),
    LDCG_CN                  VARCHAR2(20),
    STDG_CD                  VARCHAR2(10),
    PRMSN_DCLR_NO            VARCHAR2(30),
    SPCITM_CN                VARCHAR2(1000),
    LAT_DG                   VARCHAR2(20),
    LAT_MI                   VARCHAR2(20),
    LAT_SS                   VARCHAR2(20),
    LOT_DG                   VARCHAR2(20),
    LOT_MI                   VARCHAR2(20),
    LOT_SS                   VARCHAR2(20),
    XCRD                     NUMBER(10),
    YCRD                     NUMBER(10),
    PRMSN_DCLR_CLSF_CN      VARCHAR2(20),
    USER_NM                  VARCHAR2(100),
    USER_ADDR                VARCHAR2(100),
    GWEL_USE_CN              VARCHAR2(4000),
    WTSPL_STTS_CLSF_CN      VARCHAR2(20),
    EQPMNT_INSTL_YN_CN      VARCHAR2(10),
    EQPMNT_INSTL_PSBLTY_CN  VARCHAR2(10),
    EQPMNT_INSTL_IMPS_CN    VARCHAR2(500),
    PRMSN_DCLR_USG_CN       VARCHAR2(100),
    PRMSN_DCLR_DTL_USG_CN   VARCHAR2(100),
    UGWTR_USG_CN             VARCHAR2(500),
    UGWTR_DTL_USG_CN         VARCHAR2(100),
    DKPP_YN                  CHAR(1),
    YR_USQTY_CN              VARCHAR2(20),
    MAIN_USE_PRD             VARCHAR2(20),
    USE_CN                   VARCHAR2(500),
    WTRTRM_CN                VARCHAR2(8),
    RMRK                     VARCHAR2(500),
    ENG_GRNDS_EXMN_NO       VARCHAR2(100),
    FMT_INSTL_CN             VARCHAR2(1000),
    INSTL_YMD                VARCHAR2(8),
    LCLGV_CD                 VARCHAR2(7),
    FRST_REG_DT              DATE,
    OBSVTR_ID                VARCHAR2(30),
    USE_USG_SNTHS_CN         VARCHAR2(1000),
    WTOBS_CD                 VARCHAR2(3),
    UGWTR_USE_RT_CNT         NUMBER(22),
    FCLT_FRM_CLSF_CN         VARCHAR2(4000),
    PUMP_FRM_CLSF_CN         VARCHAR2(4000),
    FCLT_CL_CN               VARCHAR2(4000),
    FMT_STTS_CLSF_CN         VARCHAR2(4000),
    DGG_DPTH                 NUMBER(10),
    DGG_CALBR                NUMBER(10),
    PUMP_VL                  NUMBER(10),
    FLDEVT_EQPMNT_EN_CN     VARCHAR2(1000),
    WPMP_ABLT                NUMBER(10),
    WTRIT_PLNQTY             NUMBER(22),
    FMT_SPCFCT_VL            NUMBER(10),
    CALBR_MSRMT_MTHD_CN     VARCHAR2(4000),
    CALBR                    NUMBER(10),
    TRSM_EQPMNT_INSTL_MTHD_CN VARCHAR2(100),
    CAL_USQTY_VL             NUMBER(22),
    USE_YN                   CHAR(1),
    REG_ID                   VARCHAR2(50)
);

-- MERGE 키 유니크 인덱스
CREATE UNIQUE INDEX UQ_TM_GD111010_PRMSN ON TM_GD111010(PRMSN_DCLR_NO);
-- OBSVTR_ID 조회용 인덱스
CREATE INDEX IDX_TM_GD111010_OBSVTR ON TM_GD111010(OBSVTR_ID);

-- 코멘트
COMMENT ON COLUMN TM_GD111010.INSTL_PSBLTY_FMT_CN IS '설치가능유량계내용';
COMMENT ON COLUMN TM_GD111010.GRNDS_GWEL_NO IS '현장관정번호';
COMMENT ON COLUMN TM_GD111010.EXMN_YMD IS '조사일자';
COMMENT ON COLUMN TM_GD111010.EXMNR_NM IS '조사자명';
COMMENT ON COLUMN TM_GD111010.CTPV_NM IS '시도명';
COMMENT ON COLUMN TM_GD111010.SGG_NM IS '시군구명';
COMMENT ON COLUMN TM_GD111010.EMD_NM IS '읍면동명';
COMMENT ON COLUMN TM_GD111010.LI_NM IS '리명';
COMMENT ON COLUMN TM_GD111010.BNJ IS '번지';
COMMENT ON COLUMN TM_GD111010.GRNDS_BNJ_CN IS '현장번지내용';
COMMENT ON COLUMN TM_GD111010.ARND_LOTNO_CN IS '주변지번내용';
COMMENT ON COLUMN TM_GD111010.LDCG_CN IS '지목내용';
COMMENT ON COLUMN TM_GD111010.STDG_CD IS '법정동코드';
COMMENT ON COLUMN TM_GD111010.PRMSN_DCLR_NO IS '허가신고번호';
COMMENT ON COLUMN TM_GD111010.SPCITM_CN IS '특이사항내용';
COMMENT ON COLUMN TM_GD111010.LAT_DG IS '위도도';
COMMENT ON COLUMN TM_GD111010.LAT_MI IS '위도분';
COMMENT ON COLUMN TM_GD111010.LAT_SS IS '위도초';
COMMENT ON COLUMN TM_GD111010.LOT_DG IS '경도도';
COMMENT ON COLUMN TM_GD111010.LOT_MI IS '경도분';
COMMENT ON COLUMN TM_GD111010.LOT_SS IS '경도초';
COMMENT ON COLUMN TM_GD111010.XCRD IS 'X좌표';
COMMENT ON COLUMN TM_GD111010.YCRD IS 'Y좌표';
COMMENT ON COLUMN TM_GD111010.PRMSN_DCLR_CLSF_CN IS '허가신고분류내용';
COMMENT ON COLUMN TM_GD111010.USER_NM IS '사용자명';
COMMENT ON COLUMN TM_GD111010.USER_ADDR IS '사용자주소';
COMMENT ON COLUMN TM_GD111010.GWEL_USE_CN IS '관정사용내용';
COMMENT ON COLUMN TM_GD111010.WTSPL_STTS_CLSF_CN IS '상수도상태분류내용';
COMMENT ON COLUMN TM_GD111010.EQPMNT_INSTL_YN_CN IS '장비설치여부내용';
COMMENT ON COLUMN TM_GD111010.EQPMNT_INSTL_PSBLTY_CN IS '장비설치가능내용';
COMMENT ON COLUMN TM_GD111010.EQPMNT_INSTL_IMPS_CN IS '장비설치불가내용';
COMMENT ON COLUMN TM_GD111010.PRMSN_DCLR_USG_CN IS '허가신고용도내용';
COMMENT ON COLUMN TM_GD111010.PRMSN_DCLR_DTL_USG_CN IS '허가신고상세용도내용';
COMMENT ON COLUMN TM_GD111010.UGWTR_USG_CN IS '지하수용도내용';
COMMENT ON COLUMN TM_GD111010.UGWTR_DTL_USG_CN IS '지하수상세용도내용';
COMMENT ON COLUMN TM_GD111010.DKPP_YN IS '음용여부';
COMMENT ON COLUMN TM_GD111010.YR_USQTY_CN IS '년사용내용';
COMMENT ON COLUMN TM_GD111010.MAIN_USE_PRD IS '주사용기간';
COMMENT ON COLUMN TM_GD111010.USE_CN IS '사용내용';
COMMENT ON COLUMN TM_GD111010.WTRTRM_CN IS '정수처리내용';
COMMENT ON COLUMN TM_GD111010.RMRK IS '비고';
COMMENT ON COLUMN TM_GD111010.ENG_GRNDS_EXMN_NO IS '영문현장조사번호';
COMMENT ON COLUMN TM_GD111010.FMT_INSTL_CN IS '유량계설치내용';
COMMENT ON COLUMN TM_GD111010.INSTL_YMD IS '설치일자';
COMMENT ON COLUMN TM_GD111010.LCLGV_CD IS '지자체코드';
COMMENT ON COLUMN TM_GD111010.FRST_REG_DT IS '최초등록일시';
COMMENT ON COLUMN TM_GD111010.OBSVTR_ID IS '관측소아이디';
COMMENT ON COLUMN TM_GD111010.USE_USG_SNTHS_CN IS '사용용도종합내용';
COMMENT ON COLUMN TM_GD111010.WTOBS_CD IS '기상관측소코드';
COMMENT ON COLUMN TM_GD111010.UGWTR_USE_RT_CNT IS '지하수사용비율수';
COMMENT ON COLUMN TM_GD111010.FCLT_FRM_CLSF_CN IS '시설형태분류내용';
COMMENT ON COLUMN TM_GD111010.PUMP_FRM_CLSF_CN IS '펌프형태분류내용';
COMMENT ON COLUMN TM_GD111010.FCLT_CL_CN IS '시설분류내용';
COMMENT ON COLUMN TM_GD111010.FMT_STTS_CLSF_CN IS '유량계상태분류내용';
COMMENT ON COLUMN TM_GD111010.DGG_DPTH IS '굴착깊이';
COMMENT ON COLUMN TM_GD111010.DGG_CALBR IS '굴착구경';
COMMENT ON COLUMN TM_GD111010.PUMP_VL IS '펌프값';
COMMENT ON COLUMN TM_GD111010.FLDEVT_EQPMNT_EN_CN IS '출수장비유무내용';
COMMENT ON COLUMN TM_GD111010.WPMP_ABLT IS '양수능력';
COMMENT ON COLUMN TM_GD111010.WTRIT_PLNQTY IS '취수계획량';
COMMENT ON COLUMN TM_GD111010.FMT_SPCFCT_VL IS '유량계규격값';
COMMENT ON COLUMN TM_GD111010.CALBR_MSRMT_MTHD_CN IS '구경측정방법내용';
COMMENT ON COLUMN TM_GD111010.CALBR IS '구경';
COMMENT ON COLUMN TM_GD111010.TRSM_EQPMNT_INSTL_MTHD_CN IS '전송장비설치방법내용';
COMMENT ON COLUMN TM_GD111010.CAL_USQTY_VL IS '계산사용량값';
COMMENT ON COLUMN TM_GD111010.USE_YN IS '사용여부';
COMMENT ON COLUMN TM_GD111010.REG_ID IS '등록아이디';

COMMIT;
