
  CREATE UNIQUE INDEX "K1M"."PK_EXECUTION" ON "K1M"."EXECUTION" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_EXECUTION_EID" ON "K1M"."EXECUTION" ("EXECUTION_ID")



  CREATE INDEX "K1M"."IDX_IF_RSV_RGETHKMIR01_EID" ON "K1M"."IF_RSV_RGETHKMIR01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_IF_RSV_RGETHKMIR01" ON "K1M"."IF_RSV_RGETHKMIR01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_RGETHKMIR01_SR" ON "K1M"."IF_RSV_RGETHKMIR01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_IF_RSV_RGETNJHMS01_EID" ON "K1M"."IF_RSV_RGETNJHMS01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_IF_RSV_RGETNJHMS01" ON "K1M"."IF_RSV_RGETNJHMS01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_RGETNJHMS01_SR" ON "K1M"."IF_RSV_RGETNJHMS01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_IF_RSV_RGETNKCNO01_EID" ON "K1M"."IF_RSV_RGETNKCNO01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_IF_RSV_RGETNKCNO01" ON "K1M"."IF_RSV_RGETNKCNO01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_RGETNKCNO01_SR" ON "K1M"."IF_RSV_RGETNKCNO01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_IF_RSV_RGETNKMTB01_EID" ON "K1M"."IF_RSV_RGETNKMTB01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_IF_RSV_RGETNKMTB01" ON "K1M"."IF_RSV_RGETNKMTB01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_RGETNKMTB01_SR" ON "K1M"."IF_RSV_RGETNKMTB01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_IF_RSV_RGETNMNFE01_EID" ON "K1M"."IF_RSV_RGETNMNFE01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_IF_RSV_RGETNMNFE01" ON "K1M"."IF_RSV_RGETNMNFE01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_RGETNMNFE01_SR" ON "K1M"."IF_RSV_RGETNMNFE01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_IF_RSV_RGETNOPMS01_EID" ON "K1M"."IF_RSV_RGETNOPMS01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_IF_RSV_RGETNOPMS01" ON "K1M"."IF_RSV_RGETNOPMS01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_RGETNOPMS01_SR" ON "K1M"."IF_RSV_RGETNOPMS01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_IF_RSV_RGETNPMMS01_EID" ON "K1M"."IF_RSV_RGETNPMMS01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_IF_RSV_RGETNPMMS01" ON "K1M"."IF_RSV_RGETNPMMS01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_RGETNPMMS01_SR" ON "K1M"."IF_RSV_RGETNPMMS01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_IF_RSV_RGETNSCKT01_EID" ON "K1M"."IF_RSV_RGETNSCKT01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_IF_RSV_RGETNSCKT01" ON "K1M"."IF_RSV_RGETNSCKT01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_RGETNSCKT01_SR" ON "K1M"."IF_RSV_RGETNSCKT01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_IF_RSV_RGETNSIMS01_EID" ON "K1M"."IF_RSV_RGETNSIMS01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_IF_RSV_RGETNSIMS01" ON "K1M"."IF_RSV_RGETNSIMS01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_RGETNSIMS01_SR" ON "K1M"."IF_RSV_RGETNSIMS01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_IF_RSV_RGETNTGMS02_EID" ON "K1M"."IF_RSV_RGETNTGMS02" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_IF_RSV_RGETNTGMS02" ON "K1M"."IF_RSV_RGETNTGMS02" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_RGETNTGMS02_SR" ON "K1M"."IF_RSV_RGETNTGMS02" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_IF_RSV_RGETNWAMS01_EID" ON "K1M"."IF_RSV_RGETNWAMS01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_IF_RSV_RGETNWAMS01" ON "K1M"."IF_RSV_RGETNWAMS01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_RGETNWAMS01_SR" ON "K1M"."IF_RSV_RGETNWAMS01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_IF_RSV_RGETNWAVI05_EID" ON "K1M"."IF_RSV_RGETNWAVI05" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_IF_RSV_RGETNWAVI05" ON "K1M"."IF_RSV_RGETNWAVI05" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_RGETNWAVI05_SR" ON "K1M"."IF_RSV_RGETNWAVI05" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_IF_RSV_RGETNWAVI06_EID" ON "K1M"."IF_RSV_RGETNWAVI06" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_IF_RSV_RGETNWAVI06" ON "K1M"."IF_RSV_RGETNWAVI06" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_RGETNWAVI06_SR" ON "K1M"."IF_RSV_RGETNWAVI06" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_IF_RSV_RGETNYCSG01_EID" ON "K1M"."IF_RSV_RGETNYCSG01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_IF_RSV_RGETNYCSG01" ON "K1M"."IF_RSV_RGETNYCSG01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_RGETNYCSG01_SR" ON "K1M"."IF_RSV_RGETNYCSG01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_IF_RSV_RGETNYYMS01_EID" ON "K1M"."IF_RSV_RGETNYYMS01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_IF_RSV_RGETNYYMS01" ON "K1M"."IF_RSV_RGETNYYMS01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_RGETNYYMS01_SR" ON "K1M"."IF_RSV_RGETNYYMS01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_IF_RSV_RGETSTGMS01_EID" ON "K1M"."IF_RSV_RGETSTGMS01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_IF_RSV_RGETSTGMS01" ON "K1M"."IF_RSV_RGETSTGMS01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_RGETSTGMS01_SR" ON "K1M"."IF_RSV_RGETSTGMS01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_IF_RSV_JEWON_EXEC" ON "K1M"."IF_RSV_SEC_JEWON" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."SYS_C008320" ON "K1M"."IF_RSV_SEC_JEWON" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_JEWON_SREFS" ON "K1M"."IF_RSV_SEC_JEWON" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_IF_RSV_OBSV_EXEC" ON "K1M"."IF_RSV_SEC_OBSVDATA" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."SYS_C008326" ON "K1M"."IF_RSV_SEC_OBSVDATA" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_OBSV_SREFS" ON "K1M"."IF_RSV_SEC_OBSVDATA" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_RSV_TB_JEJU_EID" ON "K1M"."IF_RSV_TB_JEJU" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."SYS_C008435" ON "K1M"."IF_RSV_TB_JEJU" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_TB_JEJU_SR" ON "K1M"."IF_RSV_TB_JEJU" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_RSV_JEJU_JEWON_EID" ON "K1M"."IF_RSV_TB_JEJU_JEWON" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."SYS_C008432" ON "K1M"."IF_RSV_TB_JEJU_JEWON" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_JEJU_JEWON_SR" ON "K1M"."IF_RSV_TB_JEJU_JEWON" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_RSV_USE_JEJUDAY_EID" ON "K1M"."IF_RSV_USE_JEJU_DAY" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."SYS_C008444" ON "K1M"."IF_RSV_USE_JEJU_DAY" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_USE_JEJUDAY_SR" ON "K1M"."IF_RSV_USE_JEJU_DAY" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_RSV_USE_LEGACY_EID" ON "K1M"."IF_RSV_USE_LEGACY_DATA" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."SYS_C008438" ON "K1M"."IF_RSV_USE_LEGACY_DATA" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_USE_LEGACY_SR" ON "K1M"."IF_RSV_USE_LEGACY_DATA" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_RSV_USE_STATUS_EID" ON "K1M"."IF_RSV_USE_STATUS_DATA" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."SYS_C008441" ON "K1M"."IF_RSV_USE_STATUS_DATA" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_IF_RSV_USE_STATUS_SR" ON "K1M"."IF_RSV_USE_STATUS_DATA" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_PM_GD111021_EID" ON "K1M"."PM_GD111021" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_PM_GD111021" ON "K1M"."PM_GD111021" ("BRNCH_ID", "OBSRVN_DT")



  CREATE INDEX "K1M"."IDX_PM_GD111022_EID" ON "K1M"."PM_GD111022" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_PM_GD111022" ON "K1M"."PM_GD111022" ("BRNCH_ID", "OBSRVN_YMD")



  CREATE INDEX "K1M"."IDX_PM_GD970201_EID" ON "K1M"."PM_GD970201" ("EXECUTION_ID")



  CREATE INDEX "K1M"."IDX_PM_GD970201_OBSRVN_DT" ON "K1M"."PM_GD970201" ("OBSRVN_DT")



  CREATE INDEX "K1M"."IDX_PM_GD970201_RSLT_ID" ON "K1M"."PM_GD970201" ("RSLT_ID")



  CREATE UNIQUE INDEX "K1M"."PK_PM_GD970201" ON "K1M"."PM_GD970201" ("OBSRVN_DATA_ID")



  CREATE INDEX "K1M"."IDX_PM_GD970202_EID" ON "K1M"."PM_GD970202" ("EXECUTION_ID")



  CREATE INDEX "K1M"."IDX_PM_GD970202_OBSRVN_DT" ON "K1M"."PM_GD970202" ("OBSRVN_DT")



  CREATE INDEX "K1M"."IDX_PM_GD970202_RSLT_ID" ON "K1M"."PM_GD970202" ("RSLT_ID")



  CREATE UNIQUE INDEX "K1M"."PK_PM_GD970202" ON "K1M"."PM_GD970202" ("OBSRVN_DATA_ID")



  CREATE INDEX "K1M"."IDX_GIMS_RGETHKMIR01_EID" ON "K1M"."RGETHKMIR01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_GIMS_RGETHKMIR01" ON "K1M"."RGETHKMIR01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_GIMS_RGETHKMIR01_SR" ON "K1M"."RGETHKMIR01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_GIMS_RGETNJHMS01_EID" ON "K1M"."RGETNJHMS01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_GIMS_RGETNJHMS01" ON "K1M"."RGETNJHMS01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_GIMS_RGETNJHMS01_SR" ON "K1M"."RGETNJHMS01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_GIMS_RGETNKCNO01_EID" ON "K1M"."RGETNKCNO01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_GIMS_RGETNKCNO01" ON "K1M"."RGETNKCNO01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_GIMS_RGETNKCNO01_SR" ON "K1M"."RGETNKCNO01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_GIMS_RGETNKMTB01_EID" ON "K1M"."RGETNKMTB01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_GIMS_RGETNKMTB01" ON "K1M"."RGETNKMTB01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_GIMS_RGETNKMTB01_SR" ON "K1M"."RGETNKMTB01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_GIMS_RGETNMNFE01_EID" ON "K1M"."RGETNMNFE01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_GIMS_RGETNMNFE01" ON "K1M"."RGETNMNFE01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_GIMS_RGETNMNFE01_SR" ON "K1M"."RGETNMNFE01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_GIMS_RGETNOPMS01_EID" ON "K1M"."RGETNOPMS01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_GIMS_RGETNOPMS01" ON "K1M"."RGETNOPMS01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_GIMS_RGETNOPMS01_SR" ON "K1M"."RGETNOPMS01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_GIMS_RGETNPMMS01_EID" ON "K1M"."RGETNPMMS01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_GIMS_RGETNPMMS01" ON "K1M"."RGETNPMMS01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_GIMS_RGETNPMMS01_SR" ON "K1M"."RGETNPMMS01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_GIMS_RGETNSCKT01_EID" ON "K1M"."RGETNSCKT01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_GIMS_RGETNSCKT01" ON "K1M"."RGETNSCKT01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_GIMS_RGETNSCKT01_SR" ON "K1M"."RGETNSCKT01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_GIMS_RGETNSIMS01_EID" ON "K1M"."RGETNSIMS01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_GIMS_RGETNSIMS01" ON "K1M"."RGETNSIMS01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_GIMS_RGETNSIMS01_SR" ON "K1M"."RGETNSIMS01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_GIMS_RGETNTGMS02_EID" ON "K1M"."RGETNTGMS02" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_GIMS_RGETNTGMS02" ON "K1M"."RGETNTGMS02" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_GIMS_RGETNTGMS02_SR" ON "K1M"."RGETNTGMS02" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_GIMS_RGETNWAMS01_EID" ON "K1M"."RGETNWAMS01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_GIMS_RGETNWAMS01" ON "K1M"."RGETNWAMS01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_GIMS_RGETNWAMS01_SR" ON "K1M"."RGETNWAMS01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_GIMS_RGETNWAVI05_EID" ON "K1M"."RGETNWAVI05" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_GIMS_RGETNWAVI05" ON "K1M"."RGETNWAVI05" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_GIMS_RGETNWAVI05_SR" ON "K1M"."RGETNWAVI05" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_GIMS_RGETNWAVI06_EID" ON "K1M"."RGETNWAVI06" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_GIMS_RGETNWAVI06" ON "K1M"."RGETNWAVI06" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_GIMS_RGETNWAVI06_SR" ON "K1M"."RGETNWAVI06" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_GIMS_RGETNYCSG01_EID" ON "K1M"."RGETNYCSG01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_GIMS_RGETNYCSG01" ON "K1M"."RGETNYCSG01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_GIMS_RGETNYCSG01_SR" ON "K1M"."RGETNYCSG01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_GIMS_RGETNYYMS01_EID" ON "K1M"."RGETNYYMS01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_GIMS_RGETNYYMS01" ON "K1M"."RGETNYYMS01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_GIMS_RGETNYYMS01_SR" ON "K1M"."RGETNYYMS01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_GIMS_RGETSTGMS01_EID" ON "K1M"."RGETSTGMS01" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_GIMS_RGETSTGMS01" ON "K1M"."RGETSTGMS01" ("ID")



  CREATE UNIQUE INDEX "K1M"."UK_GIMS_RGETSTGMS01_SR" ON "K1M"."RGETSTGMS01" ("SOURCE_REFS")



  CREATE INDEX "K1M"."IDX_SYNC_LOG_EXEC" ON "K1M"."SYNC_LOG" ("EXECUTION_ID")



  CREATE INDEX "K1M"."IDX_SYNC_LOG_MAP" ON "K1M"."SYNC_LOG" ("EXECUTION_ID", "MAPPING_NAME")



  CREATE UNIQUE INDEX "K1M"."PK_SYNC_LOG" ON "K1M"."SYNC_LOG" ("ID")



  CREATE INDEX "K1M"."IDX_TM_GD111010_EID" ON "K1M"."TM_GD111010" ("EXECUTION_ID")



  CREATE INDEX "K1M"."IDX_TM_GD111010_TELNO" ON "K1M"."TM_GD111010" ("TELNO")



  CREATE UNIQUE INDEX "K1M"."PK_TM_GD111010" ON "K1M"."TM_GD111010" ("BRNCH_ID")



  CREATE INDEX "K1M"."IDX_TM_GD111024_EID" ON "K1M"."TM_GD111024" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_TM_GD111024" ON "K1M"."TM_GD111024" ("BRNCH_ID")



  CREATE INDEX "K1M"."IDX_TM_GD111025_EID" ON "K1M"."TM_GD111025" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_TM_GD111025" ON "K1M"."TM_GD111025" ("SN")



  CREATE INDEX "K1M"."IDX_TM_GD120001_EID" ON "K1M"."TM_GD120001" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_TM_GD120001" ON "K1M"."TM_GD120001" ("GWEL_NO")



  CREATE UNIQUE INDEX "K1M"."UK_TM_GD120001_GRNDS" ON "K1M"."TM_GD120001" ("GRNDS_GWEL_NO", "UGWTR_EXMN_CD")



  CREATE INDEX "K1M"."IDX_TM_GD970001_BRNCH_TYPE" ON "K1M"."TM_GD970001" ("BRNCH_TYPE_MNG_TRM_NM")



  CREATE INDEX "K1M"."IDX_TM_GD970001_EID" ON "K1M"."TM_GD970001" ("EXECUTION_ID")



  CREATE INDEX "K1M"."IDX_TM_GD970001_OBSVTR_ID" ON "K1M"."TM_GD970001" ("OBSVTR_ID")



  CREATE UNIQUE INDEX "K1M"."PK_TM_GD970001" ON "K1M"."TM_GD970001" ("BRNCH_ID")



  CREATE INDEX "K1M"."IDX_TM_GD970002_EID" ON "K1M"."TM_GD970002" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_TM_GD970002" ON "K1M"."TM_GD970002" ("BRNCH_ID")



  CREATE INDEX "K1M"."IDX_TM_GD970101_BRNCH_ID" ON "K1M"."TM_GD970101" ("BRNCH_ID")



  CREATE INDEX "K1M"."IDX_TM_GD970101_EID" ON "K1M"."TM_GD970101" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_TM_GD970101" ON "K1M"."TM_GD970101" ("RSLT_ID")



  CREATE UNIQUE INDEX "K1M"."UK_TM_GD970101" ON "K1M"."TM_GD970101" ("HR_UNIT_ID", "OBSRVN_ARTCL_ID", "BRNCH_ID")



  CREATE INDEX "K1M"."IDX_TM_GD970130_BRNCH" ON "K1M"."TM_GD970130" ("BRNCH_ID")



  CREATE INDEX "K1M"."IDX_TM_GD970130_EID" ON "K1M"."TM_GD970130" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_TM_GD970130" ON "K1M"."TM_GD970130" ("GWEL_NO", "BRNCH_ID")



  CREATE INDEX "K1M"."IDX_TM_GD980002_EID" ON "K1M"."TM_GD980002" ("EXECUTION_ID")



  CREATE UNIQUE INDEX "K1M"."PK_TM_GD980002" ON "K1M"."TM_GD980002" ("OBSVTR_ID")


