server:
  port: 8084

spring:
  application:
    name: infolink-api-collector

  datasource:
    url: ENC(JuW0/2U2bSAtEGNxxn6FkZQgf18EHzqKPd+r+mfceiPBw05AWmQ2zn+FUTxnwSdjI335KfxJxziJ9C2omOr2eOaDX5K+aGNNEskOwv6nh0E=)
    username: ENC(yFdNzBUZC56DfPjongW3r4yZxc641T+kyQFmCC8Xf+dLAj0ckvN/G4qaVihVIpn9)
    password: ENC(PaubXinnwCX+svepYBVcdW4TNidVHQDR+UPQJkkrDrj6wnDZPR9TExuVMEST6m0A)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

# Jasypt 암호화 설정
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
    algorithm: PBEWithHMACSHA512AndAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator

logging:
  level:
    com.infolink.collector: DEBUG
    org.hibernate.SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: h2

  datasource:
    url: jdbc:h2:mem:api_collector;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
