server:
  port: 8080

spring:
  application:
    name: sync-orchestrator

  datasource:
    url: jdbc:postgresql://localhost:29001/orchestrator
    username: ENC(EDM5TL2kOyQiRFRd9jESbpEI2D5xiI39lrtus7w21+HokNEBVH//QAudBWulnwkW)
    password: ENC(hqhtiytYUEOFiwvWrzC1/VpX4LSBz9izPItGydeOdcngRI5FUnI3U2wwYLiUEXfB)
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

# Retention(자동삭제) 스케줄
retention:
  cron: "0 0 2 * * *"  # 매일 새벽 2시

# Jasypt 암호화 설정
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD:sync-pipeline-secret-key-2024}
    algorithm: PBEWithHMACSHA512AndAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator

# Actuator 모니터링
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,threaddump,env
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.sync: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
