-- ──────────────────────────────────────────────────────────
-- B5 SupplementaryGroundwater 핸들러용 샘플 데이터 (6 테이블 JOIN 정합)
-- 기준: GWEL_NO=10001 (TM_GD120001 노원 — 기존)
-- 신규 INSERT: TM_GD970101/970130/970001/970002/980002 (BRNCH_ID=1 매칭)
-- ──────────────────────────────────────────────────────────

-- 1. TM_GD970101 (ODM 결과) — TAG_CN = GWEL_NO 매칭 (NUMBER↔VARCHAR2 형변환)
INSERT INTO TM_GD970101 (TAG_CN, BRNCH_ID)
SELECT '10001', 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TM_GD970101 WHERE TAG_CN='10001' AND BRNCH_ID=1);

-- 2. TM_GD970130 (ODM 관정사양) — GWEL_NO=10001, BRNCH_ID=1
MERGE INTO TM_GD970130 t USING (SELECT 10001 AS GWEL_NO, 1 AS BRNCH_ID FROM DUAL) s
ON (t.GWEL_NO = s.GWEL_NO AND t.BRNCH_ID = s.BRNCH_ID)
WHEN NOT MATCHED THEN INSERT
  (GWEL_NO, BRNCH_ID, INSTL_DPH_VL, UPPRT_DGG_CALBR, OBSRVN_ARTCL_NM, OBSRVN_CYCL_CN,
   UGWTR_DTL_USG_CD, DKPP_YN, PRMSN_DCLR_NO, CSNG_HGT)
VALUES
  (s.GWEL_NO, s.BRNCH_ID, 80, 200, '수위/수온/EC', '시간별',
   '01', 'Y', 'PWD-2025-0001', 0.5);
COMMIT;

-- 3. TM_GD970001 (ODM 관측소) — BRNCH_ID=1, BRNCH_TYPE_MNG_TRM_NM='보조지하수관측망'
MERGE INTO TM_GD970001 t USING (SELECT 1 AS BRNCH_ID FROM DUAL) s
ON (t.BRNCH_ID = s.BRNCH_ID)
WHEN NOT MATCHED THEN INSERT
  (BRNCH_ID, OBSVTR_ID, OBSVTR_NM, INSTL_YMD, RMRK_CN, FRST_REG_DT, BRNCH_TYPE_MNG_TRM_NM)
VALUES
  (s.BRNCH_ID, 'OBS-NWN-001', '노원 보조관측소', '20240101', '샘플 보조관측망', SYSDATE, '보조지하수관측망');
COMMIT;

-- 4. TM_GD970002 (ODM 관측소사양) — BRNCH_ID=1
MERGE INTO TM_GD970002 t USING (SELECT 1 AS BRNCH_ID FROM DUAL) s
ON (t.BRNCH_ID = s.BRNCH_ID)
WHEN NOT MATCHED THEN INSERT
  (BRNCH_ID, MGAGC_NM, RDNM)
VALUES
  (s.BRNCH_ID, '서울특별시 노원구청', '상계로 12');
COMMIT;

-- 5. TM_GD980002 (보조수위측정망 연계) — BRNCH_ID=1
MERGE INTO TM_GD980002 t USING (SELECT 1 AS BRNCH_ID FROM DUAL) s
ON (t.BRNCH_ID = s.BRNCH_ID)
WHEN NOT MATCHED THEN INSERT
  (BRNCH_ID, LINK_TRGT_IP, LINK_TRGT_PORT_CN)
VALUES
  (s.BRNCH_ID, '10.0.0.1', '8080');
COMMIT;

-- 검증 — 핸들러 SQL 직접 실행
SELECT GWEL_NO AS GENNUM,
       OBSV_NAME AS JIGUNAME,
       OBSV_CODE,
       INPERM_NO,
       SIDO || ' ' || SIGUNGU || ' ' || UPMYUNDO || ' ' || NVL(RI, '') AS ADDR,
       PYOGO,
       MGR_ORG AS SOUR_GOV,
       INSDATE,
       OBSV_TYPE,
       WELL,
       CASING_HEIGHT,
       GULDEP,
       GULDIA,
       GIGWANMETHOD,
       GIGWANITEM,
       YONGDO_CD AS GROUNDUSE,
       UMYONG AS UWATER_POTA_YN
FROM (
  SELECT TB3.OBSVTR_ID AS OBSV_CODE,
         TB1.STDG_CD AS REGION_CODE,
         TB3.OBSVTR_NM AS OBSV_NAME,
         TB1.CTPV_NM AS SIDO,
         TB1.SGG_NM AS SIGUNGU,
         TB1.EMD_NM AS UPMYUNDO,
         TB1.LI_NM AS RI,
         TB1.ADDR AS BUNJI,
         TB4.RDNM AS ROADADDR,
         TB1.LAT AS X,
         TB1.LOT AS Y,
         TB1.ALTD_VL AS PYOGO,
         TB4.MGAGC_NM AS MGR_ORG,
         TB3.INSTL_YMD AS INSDATE,
         TB3.RMRK_CN AS REMARK,
         TB1.GWEL_FRM_CD AS WELL,
         TB2.INSTL_DPH_VL AS GULDEP,
         TB2.UPPRT_DGG_CALBR AS GULDIA,
         TB2.OBSRVN_ARTCL_NM AS GIGWANITEM,
         TB2.OBSRVN_CYCL_CN AS GIGWANMETHOD,
         TB2.UGWTR_DTL_USG_CD AS YONGDO_CD,
         TB2.DKPP_YN AS UMYONG,
         TB3.FRST_REG_DT AS REGDATE,
         TB1.GWEL_NO,
         TB2.PRMSN_DCLR_NO AS INPERM_NO,
         TB1.GWEL_FRM_CD AS OBSV_TYPE,
         TB2.CSNG_HGT AS CASING_HEIGHT,
         TB5.LINK_TRGT_IP AS SEARCHDBIP,
         TB5.LINK_TRGT_PORT_CN AS SEARCHPORT
  FROM TM_GD120001 TB1
  LEFT OUTER JOIN (SELECT DISTINCT TAG_CN, BRNCH_ID FROM TM_GD970101) TB6
    ON TB1.GWEL_NO = TB6.TAG_CN
  LEFT OUTER JOIN TM_GD970130 TB2
    ON TB6.TAG_CN = TB2.GWEL_NO
  LEFT OUTER JOIN TM_GD970001 TB3
    ON TB2.BRNCH_ID = TB3.BRNCH_ID
  LEFT OUTER JOIN TM_GD970002 TB4
    ON TB2.BRNCH_ID = TB4.BRNCH_ID
  LEFT OUTER JOIN TM_GD980002 TB5
    ON TB2.BRNCH_ID = TB5.BRNCH_ID
  WHERE TB3.BRNCH_TYPE_MNG_TRM_NM = '보조지하수관측망'
     OR TB3.BRNCH_TYPE_MNG_TRM_NM = '수동보조지하수관측망'
)
WHERE GWEL_NO = 10001;
