-- B7 WaterLevelObservationHandler / B8 RainfallObservationHandler
-- target: opn.info_observation_station1 (waterLevel) / opn.info_observation_station0 (rainfall)
-- source: DBLINKUSR.DUBWLOBSIF / DUBMMWL / V_WP_WKSDAMSBSN / V_WR_HACHEON_MST / DUBRFOBSIF / DUBMMRF
--
-- DBLINKUSR user already exists — create tables under DBLINKUSR + grant SELECT to K1M
-- Run via: sqlplus DBLINKUSR/1111@XEPDB1
--
-- B7 scenario: wlobscd='1001601' -> 1 row (level station with 10-min reading)
-- B8 scenario: rfobscd='10014010' -> 1 row (rainfall station with 10-min reading)

-- =============================================================
-- B7: water level
-- =============================================================

-- 1. DUBWLOBSIF (water level station meta)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DUBWLOBSIF CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE DUBWLOBSIF (
  WLOBSCD     VARCHAR2(20) PRIMARY KEY,
  OBSNM       VARCHAR2(100),
  MGGVCD      VARCHAR2(10),
  ADDR        VARCHAR2(500),
  LAT         VARCHAR2(20),
  LON         VARCHAR2(20),
  OPNDT       DATE,
  OBSKDCD     VARCHAR2(10),
  ODAMBSNA    NUMBER(10,2),
  MRJPDIS     NUMBER(10,2),
  ZRELM       NUMBER(10,2),
  RIVCD       VARCHAR2(20),
  SBSNCD      VARCHAR2(10)
);

-- 2. DUBMMWL (10-minute water level)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DUBMMWL CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE DUBMMWL (
  WLOBSCD     VARCHAR2(20),
  OBSDHM      VARCHAR2(12),
  TRMDV       VARCHAR2(2),
  WL          VARCHAR2(20),
  FLW         VARCHAR2(20),
  CONSTRAINT PK_DUBMMWL PRIMARY KEY (WLOBSCD, OBSDHM, TRMDV)
);

-- 3. V_WP_WKSDAMSBSN (sub-basin master)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE V_WP_WKSDAMSBSN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE V_WP_WKSDAMSBSN (
  SBSNCD       VARCHAR2(10),
  SBSNCD_OLD   VARCHAR2(10),
  SBSNCD_NM    VARCHAR2(100),
  LARGE_CODE   VARCHAR2(10),
  LARGE_CNM    VARCHAR2(100)
);

-- 4. V_WR_HACHEON_MST (river master)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE V_WR_HACHEON_MST CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE V_WR_HACHEON_MST (
  NRIVCD      VARCHAR2(20) PRIMARY KEY,
  NRIVNM      VARCHAR2(100)
);

-- =============================================================
-- B8: rainfall
-- =============================================================

-- 5. DUBRFOBSIF (rainfall station meta)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DUBRFOBSIF CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE DUBRFOBSIF (
  RFOBSCD     VARCHAR2(20) PRIMARY KEY,
  OBSNM       VARCHAR2(100),
  GVCD        VARCHAR2(10),
  ADDR        VARCHAR2(500),
  LAT         VARCHAR2(20),
  LON         VARCHAR2(20),
  OBSOPNDT    DATE,
  OBSGGTYP    VARCHAR2(20),
  SBSNCD      VARCHAR2(10)
);

-- 6. DUBMMRF (10-minute rainfall)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DUBMMRF CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
CREATE TABLE DUBMMRF (
  RFOBSCD     VARCHAR2(20),
  OBSDHM      VARCHAR2(12),
  TRMDV       VARCHAR2(2),
  RF          VARCHAR2(20),
  ACURF       VARCHAR2(20),
  CONSTRAINT PK_DUBMMRF PRIMARY KEY (RFOBSCD, OBSDHM, TRMDV)
);

-- =============================================================
-- Grant SELECT to K1M (handler runs as K1M)
-- =============================================================
GRANT SELECT ON DUBWLOBSIF       TO K1M;
GRANT SELECT ON DUBMMWL          TO K1M;
GRANT SELECT ON V_WP_WKSDAMSBSN  TO K1M;
GRANT SELECT ON V_WR_HACHEON_MST TO K1M;
GRANT SELECT ON DUBRFOBSIF       TO K1M;
GRANT SELECT ON DUBMMRF          TO K1M;

-- =============================================================
-- Sample data
-- =============================================================

-- B7 — water level station
INSERT INTO DUBWLOBSIF (WLOBSCD, OBSNM, MGGVCD, ADDR, LAT, LON, OPNDT, OBSKDCD, ODAMBSNA, MRJPDIS, ZRELM, RIVCD, SBSNCD)
VALUES ('1001601', 'GongJu (Geum River)', '11', 'Gongju-si, Chungnam', '36.456', '127.123', DATE '2010-05-01', 'WL01', 4500.55, 35.20, 12.345, 'NR001', '1010');

-- B7 — 10-min level (TRMDV=10 = 10-minute interval)
-- OBSDHM = current hour at 50/00/10/20/30/40 minute slots (actual handler computes dynamically)
-- For test we insert several recent slots so handler matches whatever current time produces
INSERT INTO DUBMMWL (WLOBSCD, OBSDHM, TRMDV, WL, FLW)
VALUES ('1001601', TO_CHAR(SYSDATE, 'YYYYMMDDHH24') || '00', '10', '5.123', '120.456');
INSERT INTO DUBMMWL (WLOBSCD, OBSDHM, TRMDV, WL, FLW)
VALUES ('1001601', TO_CHAR(SYSDATE, 'YYYYMMDDHH24') || '10', '10', '5.234', '121.567');
INSERT INTO DUBMMWL (WLOBSCD, OBSDHM, TRMDV, WL, FLW)
VALUES ('1001601', TO_CHAR(SYSDATE, 'YYYYMMDDHH24') || '20', '10', '5.345', '122.678');
INSERT INTO DUBMMWL (WLOBSCD, OBSDHM, TRMDV, WL, FLW)
VALUES ('1001601', TO_CHAR(SYSDATE, 'YYYYMMDDHH24') || '30', '10', '5.456', '123.789');
INSERT INTO DUBMMWL (WLOBSCD, OBSDHM, TRMDV, WL, FLW)
VALUES ('1001601', TO_CHAR(SYSDATE, 'YYYYMMDDHH24') || '40', '10', '5.567', '124.890');
INSERT INTO DUBMMWL (WLOBSCD, OBSDHM, TRMDV, WL, FLW)
VALUES ('1001601', TO_CHAR(SYSDATE, 'YYYYMMDDHH24') || '50', '10', '5.678', '125.901');
-- Also include previous hour for boundary cases
INSERT INTO DUBMMWL (WLOBSCD, OBSDHM, TRMDV, WL, FLW)
VALUES ('1001601', TO_CHAR(SYSDATE - 1/24, 'YYYYMMDDHH24') || '50', '10', '5.012', '119.345');

-- B7 — sub-basin
INSERT INTO V_WP_WKSDAMSBSN (SBSNCD, SBSNCD_OLD, SBSNCD_NM, LARGE_CODE, LARGE_CNM)
VALUES ('1010', '1010', 'Geum-Gongju', '10', 'Geum River System');

-- B7 — river
INSERT INTO V_WR_HACHEON_MST (NRIVCD, NRIVNM) VALUES ('NR001', 'Geum-gang');

-- B8 — rainfall station
INSERT INTO DUBRFOBSIF (RFOBSCD, OBSNM, GVCD, ADDR, LAT, LON, OBSOPNDT, OBSGGTYP, SBSNCD)
VALUES ('10014010', 'Daejeon Rainfall', '30', 'Daejeon-si Yuseong-gu', '36.371', '127.358', DATE '2012-03-15', 'TIPPING', '1010');

-- B8 — 10-min rainfall
INSERT INTO DUBMMRF (RFOBSCD, OBSDHM, TRMDV, RF, ACURF)
VALUES ('10014010', TO_CHAR(SYSDATE, 'YYYYMMDDHH24') || '00', '10', '0.50', '12.30');
INSERT INTO DUBMMRF (RFOBSCD, OBSDHM, TRMDV, RF, ACURF)
VALUES ('10014010', TO_CHAR(SYSDATE, 'YYYYMMDDHH24') || '10', '10', '0.80', '13.10');
INSERT INTO DUBMMRF (RFOBSCD, OBSDHM, TRMDV, RF, ACURF)
VALUES ('10014010', TO_CHAR(SYSDATE, 'YYYYMMDDHH24') || '20', '10', '1.20', '14.30');
INSERT INTO DUBMMRF (RFOBSCD, OBSDHM, TRMDV, RF, ACURF)
VALUES ('10014010', TO_CHAR(SYSDATE, 'YYYYMMDDHH24') || '30', '10', '0.30', '14.60');
INSERT INTO DUBMMRF (RFOBSCD, OBSDHM, TRMDV, RF, ACURF)
VALUES ('10014010', TO_CHAR(SYSDATE, 'YYYYMMDDHH24') || '40', '10', '0.10', '14.70');
INSERT INTO DUBMMRF (RFOBSCD, OBSDHM, TRMDV, RF, ACURF)
VALUES ('10014010', TO_CHAR(SYSDATE, 'YYYYMMDDHH24') || '50', '10', '0.00', '14.70');
INSERT INTO DUBMMRF (RFOBSCD, OBSDHM, TRMDV, RF, ACURF)
VALUES ('10014010', TO_CHAR(SYSDATE - 1/24, 'YYYYMMDDHH24') || '50', '10', '0.20', '11.80');

COMMIT;

PROMPT === DUBWLOBSIF ===
SELECT WLOBSCD, OBSNM, MGGVCD FROM DUBWLOBSIF;
PROMPT === DUBMMWL count ===
SELECT WLOBSCD, COUNT(*) FROM DUBMMWL GROUP BY WLOBSCD;
PROMPT === V_WP_WKSDAMSBSN ===
SELECT * FROM V_WP_WKSDAMSBSN;
PROMPT === DUBRFOBSIF ===
SELECT RFOBSCD, OBSNM FROM DUBRFOBSIF;
PROMPT === DUBMMRF count ===
SELECT RFOBSCD, COUNT(*) FROM DUBMMRF GROUP BY RFOBSCD;
