-- ──────────────────────────────────────────────────────────
-- TM_GD023001 — 미등록지하수시설 (이전: TM_GD00301)
-- 대상 API: opn.unRegitsFclySmrize (Type B17, 대전광역시 전용)
-- 핸들러 SQL 사용 컬럼만 (BRTC_NM, SIGUN_NM, USE_STTUS_CTNT, PROCESS_CTNT)
-- PK: SN (시설일련번호)
-- ──────────────────────────────────────────────────────────

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE TM_GD023001 (
            SN              NUMBER(22)    NOT NULL,
            BRTC_NM         VARCHAR2(40),
            SIGUN_NM        VARCHAR2(40),
            USE_STTUS_CTNT  VARCHAR2(10),
            PROCESS_CTNT    VARCHAR2(40),
            CONSTRAINT PK_TM_GD023001 PRIMARY KEY (SN)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

COMMENT ON TABLE  TM_GD023001                 IS '미등록지하수시설';
COMMENT ON COLUMN TM_GD023001.SN              IS '시설일련번호';
COMMENT ON COLUMN TM_GD023001.BRTC_NM         IS '시도명';
COMMENT ON COLUMN TM_GD023001.SIGUN_NM        IS '시군구명';
COMMENT ON COLUMN TM_GD023001.USE_STTUS_CTNT  IS '사용상태 (1=사용/0=미사용/2=미정의)';
COMMENT ON COLUMN TM_GD023001.PROCESS_CTNT    IS '처리내용 (허가/신고/원상복구/시설없음/NULL=미처리)';

-- 샘플 데이터: 대전광역시 + 5개 시군구 (동구/중구/서구/유성구/대덕구) × USE_STTUS_CTNT 분포
-- PROCESS_CTNT NULL 인 것만 USED/UNUSED/UNDEFINED 에 카운트됨
INSERT ALL
  INTO TM_GD023001 (SN, BRTC_NM, SIGUN_NM, USE_STTUS_CTNT, PROCESS_CTNT) VALUES (1, '대전광역시', '동구', '1', NULL)
  INTO TM_GD023001 (SN, BRTC_NM, SIGUN_NM, USE_STTUS_CTNT, PROCESS_CTNT) VALUES (2, '대전광역시', '동구', '1', NULL)
  INTO TM_GD023001 (SN, BRTC_NM, SIGUN_NM, USE_STTUS_CTNT, PROCESS_CTNT) VALUES (3, '대전광역시', '동구', '0', NULL)
  INTO TM_GD023001 (SN, BRTC_NM, SIGUN_NM, USE_STTUS_CTNT, PROCESS_CTNT) VALUES (4, '대전광역시', '동구', '2', NULL)
  INTO TM_GD023001 (SN, BRTC_NM, SIGUN_NM, USE_STTUS_CTNT, PROCESS_CTNT) VALUES (5, '대전광역시', '중구', '1', NULL)
  INTO TM_GD023001 (SN, BRTC_NM, SIGUN_NM, USE_STTUS_CTNT, PROCESS_CTNT) VALUES (6, '대전광역시', '중구', '1', NULL)
  INTO TM_GD023001 (SN, BRTC_NM, SIGUN_NM, USE_STTUS_CTNT, PROCESS_CTNT) VALUES (7, '대전광역시', '중구', '0', NULL)
  INTO TM_GD023001 (SN, BRTC_NM, SIGUN_NM, USE_STTUS_CTNT, PROCESS_CTNT) VALUES (8, '대전광역시', '서구', '1', NULL)
  INTO TM_GD023001 (SN, BRTC_NM, SIGUN_NM, USE_STTUS_CTNT, PROCESS_CTNT) VALUES (9, '대전광역시', '서구', '1', '허가')
  INTO TM_GD023001 (SN, BRTC_NM, SIGUN_NM, USE_STTUS_CTNT, PROCESS_CTNT) VALUES (10, '대전광역시', '유성구', '1', NULL)
  INTO TM_GD023001 (SN, BRTC_NM, SIGUN_NM, USE_STTUS_CTNT, PROCESS_CTNT) VALUES (11, '대전광역시', '유성구', '0', NULL)
  INTO TM_GD023001 (SN, BRTC_NM, SIGUN_NM, USE_STTUS_CTNT, PROCESS_CTNT) VALUES (12, '대전광역시', '대덕구', '0', NULL)
SELECT 1 FROM DUAL;
COMMIT;

SELECT SIGUN_NM, USE_STTUS_CTNT, COUNT(*) FROM TM_GD023001 WHERE BRTC_NM='대전광역시'
GROUP BY SIGUN_NM, USE_STTUS_CTNT ORDER BY SIGUN_NM, USE_STTUS_CTNT;
