-- ──────────────────────────────────────────────────────────
-- TM_GD110310 — 수질검사항목별기준 (이전: TM_GD30310)
-- 대상 API: searchInspection (Type B14 파일럿)
-- 실행 계정: K1M (NGW 스키마 역할)
-- 표준화: TM_GD30310 → TM_GD110310 (환경부표준 컬럼명)
--
-- 핸들러 방식 (PVD 적재 X) — 추적 컬럼 없이 운영 GIMS Oracle 의 원본 그대로 모사
-- 복합 PK: (JOSACODE, DTA_STDR_YEAR, QLTWTR_INSPCT_IEM_CODE)
-- 멱등성 원칙: 이미 테이블/컬럼/데이터가 있어도 안전하게 실행
-- ──────────────────────────────────────────────────────────

-- 1. 테이블 생성 (이미 있으면 스킵)
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE TM_GD110310 (
            JOSACODE                  NUMBER(5)     NOT NULL,
            DTA_STDR_YEAR             CHAR(4)       NOT NULL,
            QLTWTR_INSPCT_IEM_CODE    VARCHAR2(20)  NOT NULL,
            QLTWTR_INSPCT_IEM_NM      VARCHAR2(200),
            INSPCT_IEM_BHF            VARCHAR2(100),
            UNIT_NM                   VARCHAR2(50),
            QLTWTR_STDR_VL            VARCHAR2(100),
            QLTWTR_STDR_NM            VARCHAR2(200),
            RMRK                      VARCHAR2(1000),
            CONSTRAINT PK_TM_GD110310 PRIMARY KEY (JOSACODE, DTA_STDR_YEAR, QLTWTR_INSPCT_IEM_CODE)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2. 테이블/컬럼 주석
COMMENT ON TABLE TM_GD110310 IS '수질검사항목별기준';
COMMENT ON COLUMN TM_GD110310.JOSACODE                IS '조사코드';
COMMENT ON COLUMN TM_GD110310.DTA_STDR_YEAR           IS '데이터기준연도';
COMMENT ON COLUMN TM_GD110310.QLTWTR_INSPCT_IEM_CODE  IS '수질검사항목코드';
COMMENT ON COLUMN TM_GD110310.QLTWTR_INSPCT_IEM_NM    IS '수질검사항목명';
COMMENT ON COLUMN TM_GD110310.INSPCT_IEM_BHF          IS '검사항목구분';
COMMENT ON COLUMN TM_GD110310.UNIT_NM                 IS '단위명';
COMMENT ON COLUMN TM_GD110310.QLTWTR_STDR_VL          IS '수질기준값';
COMMENT ON COLUMN TM_GD110310.QLTWTR_STDR_NM          IS '수질기준명';
COMMENT ON COLUMN TM_GD110310.RMRK                    IS '비고';

-- 3. 샘플 데이터 5건 (104=국가지하수 / NGW_0026 검사항목 코드 기반)
MERGE INTO TM_GD110310 t USING (SELECT 104 AS J, '2024' AS Y, '0001' AS C FROM DUAL) s
ON (t.JOSACODE=s.J AND t.DTA_STDR_YEAR=s.Y AND t.QLTWTR_INSPCT_IEM_CODE=s.C)
WHEN NOT MATCHED THEN INSERT (JOSACODE, DTA_STDR_YEAR, QLTWTR_INSPCT_IEM_CODE, QLTWTR_INSPCT_IEM_NM, UNIT_NM, QLTWTR_STDR_VL)
VALUES (s.J, s.Y, s.C, '일반세균수', 'CFU/mL', '100');
COMMIT;

MERGE INTO TM_GD110310 t USING (SELECT 104 AS J, '2024' AS Y, '0002' AS C FROM DUAL) s
ON (t.JOSACODE=s.J AND t.DTA_STDR_YEAR=s.Y AND t.QLTWTR_INSPCT_IEM_CODE=s.C)
WHEN NOT MATCHED THEN INSERT (JOSACODE, DTA_STDR_YEAR, QLTWTR_INSPCT_IEM_CODE, QLTWTR_INSPCT_IEM_NM, UNIT_NM, QLTWTR_STDR_VL)
VALUES (s.J, s.Y, s.C, '총대장균군', 'MPN/100mL', '0');
COMMIT;

MERGE INTO TM_GD110310 t USING (SELECT 104 AS J, '2024' AS Y, '0009' AS C FROM DUAL) s
ON (t.JOSACODE=s.J AND t.DTA_STDR_YEAR=s.Y AND t.QLTWTR_INSPCT_IEM_CODE=s.C)
WHEN NOT MATCHED THEN INSERT (JOSACODE, DTA_STDR_YEAR, QLTWTR_INSPCT_IEM_CODE, QLTWTR_INSPCT_IEM_NM, UNIT_NM, QLTWTR_STDR_VL)
VALUES (s.J, s.Y, s.C, '수소이온농도', 'pH', '5.8 ~ 8.5');
COMMIT;

MERGE INTO TM_GD110310 t USING (SELECT 104 AS J, '2023' AS Y, '0042' AS C FROM DUAL) s
ON (t.JOSACODE=s.J AND t.DTA_STDR_YEAR=s.Y AND t.QLTWTR_INSPCT_IEM_CODE=s.C)
WHEN NOT MATCHED THEN INSERT (JOSACODE, DTA_STDR_YEAR, QLTWTR_INSPCT_IEM_CODE, QLTWTR_INSPCT_IEM_NM, UNIT_NM, QLTWTR_STDR_VL)
VALUES (s.J, s.Y, s.C, '염소이온', 'mg/L', '250');
COMMIT;

MERGE INTO TM_GD110310 t USING (SELECT 112 AS J, '2024' AS Y, '0046' AS C FROM DUAL) s
ON (t.JOSACODE=s.J AND t.DTA_STDR_YEAR=s.Y AND t.QLTWTR_INSPCT_IEM_CODE=s.C)
WHEN NOT MATCHED THEN INSERT (JOSACODE, DTA_STDR_YEAR, QLTWTR_INSPCT_IEM_CODE, QLTWTR_INSPCT_IEM_NM, UNIT_NM, QLTWTR_STDR_VL)
VALUES (s.J, s.Y, s.C, '탁도', 'NTU', '1');
COMMIT;

-- 최종 상태 확인
SELECT JOSACODE, DTA_STDR_YEAR, QLTWTR_INSPCT_IEM_CODE, QLTWTR_INSPCT_IEM_NM
FROM TM_GD110310 ORDER BY JOSACODE, DTA_STDR_YEAR, QLTWTR_INSPCT_IEM_CODE;
