-- ──────────────────────────────────────────────────────────
-- VIEW_GTEST — 수질측정망 통합뷰 (개발용 물리 테이블 단순화)
-- 대상 API: opn.info_general_211215 (Type B6)
-- 운영 환경: 실제 Oracle 뷰 (운영 GIMS 측 정의)
-- 개발 환경: 핸들러 SQL 호환 위해 물리 테이블로 단순화
--
-- 핸들러 SQL 사용 컬럼만 (전체 101 컬럼 중) — 13개
-- PK: GENNUM (단건 조회용)
-- ──────────────────────────────────────────────────────────

-- 1. 테이블 생성
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE VIEW_GTEST (
            GENNUM      NUMBER(22)    NOT NULL,
            SIDO        VARCHAR2(40),
            SIGUNGU     VARCHAR2(40),
            UPMYUNDO    VARCHAR2(40),
            RI          VARCHAR2(40),
            ADDR        VARCHAR2(250),
            JOSACODE    NUMBER(5),
            JIGUNAME    VARCHAR2(100),
            GWMYR       VARCHAR2(16),
            WELLNUM     VARCHAR2(50),
            GROUNDUSE   VARCHAR2(100),
            DRINKOX     VARCHAR2(1),
            GUBUN       VARCHAR2(18),
            CONSTRAINT PK_VIEW_GTEST PRIMARY KEY (GENNUM)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- 2. 컬럼 주석
COMMENT ON TABLE  VIEW_GTEST           IS '수질측정망 통합뷰 (개발 단순화)';
COMMENT ON COLUMN VIEW_GTEST.GENNUM    IS '관측소 일련번호';
COMMENT ON COLUMN VIEW_GTEST.SIDO      IS '시도';
COMMENT ON COLUMN VIEW_GTEST.SIGUNGU   IS '시군구';
COMMENT ON COLUMN VIEW_GTEST.UPMYUNDO  IS '읍면동';
COMMENT ON COLUMN VIEW_GTEST.RI        IS '리';
COMMENT ON COLUMN VIEW_GTEST.ADDR      IS '상세주소';
COMMENT ON COLUMN VIEW_GTEST.JOSACODE  IS '조사코드';
COMMENT ON COLUMN VIEW_GTEST.JIGUNAME  IS '지구명';
COMMENT ON COLUMN VIEW_GTEST.GWMYR     IS '관측년월';
COMMENT ON COLUMN VIEW_GTEST.WELLNUM   IS '관정번호';
COMMENT ON COLUMN VIEW_GTEST.GROUNDUSE IS '지하수용도';
COMMENT ON COLUMN VIEW_GTEST.DRINKOX   IS '음용여부 (Y/N)';
COMMENT ON COLUMN VIEW_GTEST.GUBUN     IS '구분';

-- 3. 샘플 데이터 3건
MERGE INTO VIEW_GTEST t USING (SELECT 10001 AS GENNUM FROM DUAL) s ON (t.GENNUM = s.GENNUM)
WHEN NOT MATCHED THEN INSERT (GENNUM, SIDO, SIGUNGU, UPMYUNDO, RI, ADDR, JOSACODE, JIGUNAME, GWMYR, WELLNUM, GROUNDUSE, DRINKOX, GUBUN)
VALUES (s.GENNUM, '서울특별시', '노원구', '상계동', NULL, '123-45', 104, '노원지구', '202401', 'NWN-01', '생활용', 'Y', '국가지하수');
COMMIT;

MERGE INTO VIEW_GTEST t USING (SELECT 10002 AS GENNUM FROM DUAL) s ON (t.GENNUM = s.GENNUM)
WHEN NOT MATCHED THEN INSERT (GENNUM, SIDO, SIGUNGU, UPMYUNDO, RI, ADDR, JOSACODE, JIGUNAME, GWMYR, WELLNUM, GROUNDUSE, DRINKOX, GUBUN)
VALUES (s.GENNUM, '부산광역시', '해운대구', '우동', NULL, '456-78', 112, '해운대지구', '202401', 'HND-02', '농어업용', 'N', '해수침투');
COMMIT;

MERGE INTO VIEW_GTEST t USING (SELECT 10003 AS GENNUM FROM DUAL) s ON (t.GENNUM = s.GENNUM)
WHEN NOT MATCHED THEN INSERT (GENNUM, SIDO, SIGUNGU, UPMYUNDO, RI, ADDR, JOSACODE, JIGUNAME, GWMYR, WELLNUM, GROUNDUSE, DRINKOX, GUBUN)
VALUES (s.GENNUM, '대전광역시', '유성구', '궁동', '신성리', '789-01', 215, '유성지구', '202312', 'YSG-03', '공업용', 'Y', '기초조사');
COMMIT;

SELECT GENNUM, SIDO, SIGUNGU, UPMYUNDO, JIGUNAME, GUBUN FROM VIEW_GTEST ORDER BY GENNUM;
