-- ──────────────────────────────────────────────────────────
-- SDE_NGWS.WT_DREAM_PERMWELL_PUBLIC_21033 — 가뭄119 인허가관정
-- 대상 API: OPN selectdroght119 (Type A4)
-- 실행 계정: SDE_NGWS (자기 스키마 DDL + K1M GRANT)
-- 실행 방법: docker exec -i gims_orchestrator_inner_oracle sqlplus -S sde_ngws/1111@//localhost:1521/XEPDB1 < 이 파일
--
-- 표준화 매핑 없음 → 이전 이름 유지 (케이스 B, 전략문서 원칙 1.2)
-- 구조: WT_DREAM_PERMWELL_PUBLIC (34컬럼) 와 동일 + OBJECTID (SDE 관례 PK)
-- 멱등성 원칙: 이미 테이블/컬럼/데이터가 있어도 안전하게 실행
-- ──────────────────────────────────────────────────────────

-- 1. 테이블 생성 (이미 있으면 스킵)
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE WT_DREAM_PERMWELL_PUBLIC_21033 (
            OBJECTID              NUMBER(10)   NOT NULL,
            LINK_TRSM_SGG_CD      VARCHAR2(7),
            PRMSN_DCLR_NO         VARCHAR2(30),
            PRMSN_DCLR_FRM_CD     CHAR(1),
            YR_SE                 CHAR(4),
            RGN_CD                VARCHAR2(10),
            CTPV_NM               VARCHAR2(40),
            SGG_NM                VARCHAR2(40),
            EMD_NM                VARCHAR2(30),
            LI_NM                 NVARCHAR2(40),
            MTN                   CHAR(1),
            BNJ                   VARCHAR2(20),
            HO                    VARCHAR2(10),
            UGWTR_USG             VARCHAR2(20),
            UGWTR_DTL_USG_CD      CHAR(2),
            DKPP_YN               CHAR(1),
            LAT_DG                VARCHAR2(20),
            LAT_MI                VARCHAR2(20),
            LAT_SS                VARCHAR2(20),
            LOT_DG                VARCHAR2(20),
            LOT_MI                VARCHAR2(20),
            LOT_SS                VARCHAR2(20),
            DPH_VL                NUMBER(10),
            DGG_CALBR             NUMBER(10),
            DELP_DIA              NUMBER(10),
            PUMP_HRSPW            NUMBER(22),
            WTRIT_PLAN_QTR        NUMBER(5),
            WPMP_ABLT             NUMBER(10),
            YR_USQTY              NUMBER(22),
            PUB_PRVTEST_SE        CHAR(1),
            WQ_INSP_YMD           VARCHAR2(8),
            WQ_INSP_RSLT          NVARCHAR2(100),
            PNU                   VARCHAR2(19),
            XCRD                  NUMBER(10),
            YCRD                  NUMBER(10),
            CONSTRAINT PK_WT_DREAM_PERMWELL_PUBLIC_21033 PRIMARY KEY (OBJECTID)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;  -- ORA-00955: 이미 존재 → 무시
END;
/

-- 2. 추적 컬럼 추가 (없는 것만)
DECLARE
    PROCEDURE add_col(p_name VARCHAR2, p_def VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE 'ALTER TABLE WT_DREAM_PERMWELL_PUBLIC_21033 ADD ' || p_name || ' ' || p_def;
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -1430 THEN RAISE; END IF;  -- ORA-01430: 이미 있음 → 무시
    END;
BEGIN
    add_col('LINK_STATUS',  'VARCHAR2(20) DEFAULT ''PENDING''');
    add_col('EXECUTION_ID', 'VARCHAR2(100)');
    add_col('SOURCE_REFS',  'VARCHAR2(4000)');
    add_col('EXTRACTED_AT', 'TIMESTAMP');
    add_col('UPDATED_AT',   'TIMESTAMP');
END;
/

-- 3. NULL인 LINK_STATUS 를 PENDING 으로 초기화
UPDATE WT_DREAM_PERMWELL_PUBLIC_21033 SET LINK_STATUS = 'PENDING' WHERE LINK_STATUS IS NULL;

-- 4. 테이블/컬럼 주석
COMMENT ON TABLE WT_DREAM_PERMWELL_PUBLIC_21033 IS '가뭄119 인허가관정 (2021.03.03 SDE 스냅샷)';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.OBJECTID           IS 'SDE 객체 ID';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.LINK_TRSM_SGG_CD   IS '연계전송시군구코드';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.PRMSN_DCLR_NO      IS '허가신고번호';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.PRMSN_DCLR_FRM_CD  IS '허가신고형태코드';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.YR_SE              IS '연도구분';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.RGN_CD             IS '지역코드';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.CTPV_NM            IS '시도명';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.SGG_NM             IS '시군구명';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.EMD_NM             IS '읍면동명';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.LI_NM              IS '리명';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.MTN                IS '산';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.BNJ                IS '번지';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.HO                 IS '호';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.UGWTR_USG          IS '지하수용도';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.UGWTR_DTL_USG_CD   IS '지하수상세용도코드';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.DKPP_YN            IS '음용여부';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.LAT_DG             IS '위도도';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.LAT_MI             IS '위도분';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.LAT_SS             IS '위도초';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.LOT_DG             IS '경도도';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.LOT_MI             IS '경도분';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.LOT_SS             IS '경도초';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.DPH_VL             IS '심도값';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.DGG_CALBR          IS '굴착구경';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.DELP_DIA           IS '토출관직경';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.PUMP_HRSPW         IS '펌프마력';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.WTRIT_PLAN_QTR     IS '취수계획분기';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.WPMP_ABLT          IS '양수능력';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.YR_USQTY           IS '년사용량';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.PUB_PRVTEST_SE     IS '공공사설구분';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.WQ_INSP_YMD        IS '수질검사일자';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.WQ_INSP_RSLT       IS '수질검사결과';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.PNU                IS 'PNU';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.XCRD               IS 'X좌표';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.YCRD               IS 'Y좌표';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.LINK_STATUS        IS '연계상태 (PENDING/SUCCESS/FAILED)';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.EXECUTION_ID       IS '실행 ID';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.SOURCE_REFS        IS '소스 참조';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.EXTRACTED_AT       IS '추출 시각';
COMMENT ON COLUMN WT_DREAM_PERMWELL_PUBLIC_21033.UPDATED_AT         IS '갱신 시각';

-- 5. 샘플 데이터 4건 (가뭄119 맥락 지역, PENDING)
MERGE INTO WT_DREAM_PERMWELL_PUBLIC_21033 t
USING (SELECT 1001 AS OBJECTID FROM DUAL) s ON (t.OBJECTID = s.OBJECTID)
WHEN NOT MATCHED THEN INSERT (
    OBJECTID, PRMSN_DCLR_NO, CTPV_NM, SGG_NM, EMD_NM, UGWTR_USG, DKPP_YN,
    DPH_VL, DGG_CALBR, PUMP_HRSPW, PUB_PRVTEST_SE, LINK_STATUS
) VALUES (
    s.OBJECTID, 'DR-119-1001', '경상북도', '안동시', '송현동', '생활용수', 'Y',
    90, 150, 5, '1', 'PENDING'
);
COMMIT;

MERGE INTO WT_DREAM_PERMWELL_PUBLIC_21033 t
USING (SELECT 1002 AS OBJECTID FROM DUAL) s ON (t.OBJECTID = s.OBJECTID)
WHEN NOT MATCHED THEN INSERT (
    OBJECTID, PRMSN_DCLR_NO, CTPV_NM, SGG_NM, EMD_NM, UGWTR_USG, DKPP_YN,
    DPH_VL, DGG_CALBR, PUMP_HRSPW, PUB_PRVTEST_SE, LINK_STATUS
) VALUES (
    s.OBJECTID, 'DR-119-1002', '경상북도', '포항시', '대보리', '농업용수', 'N',
    110, 200, 7, '2', 'PENDING'
);
COMMIT;

MERGE INTO WT_DREAM_PERMWELL_PUBLIC_21033 t
USING (SELECT 1003 AS OBJECTID FROM DUAL) s ON (t.OBJECTID = s.OBJECTID)
WHEN NOT MATCHED THEN INSERT (
    OBJECTID, PRMSN_DCLR_NO, CTPV_NM, SGG_NM, EMD_NM, UGWTR_USG, DKPP_YN,
    DPH_VL, DGG_CALBR, PUMP_HRSPW, PUB_PRVTEST_SE, LINK_STATUS
) VALUES (
    s.OBJECTID, 'DR-119-1003', '전라남도', '신안군', '흑산면', '생활용수', 'Y',
    60, 120, 3, '1', 'PENDING'
);
COMMIT;

MERGE INTO WT_DREAM_PERMWELL_PUBLIC_21033 t
USING (SELECT 1004 AS OBJECTID FROM DUAL) s ON (t.OBJECTID = s.OBJECTID)
WHEN NOT MATCHED THEN INSERT (
    OBJECTID, PRMSN_DCLR_NO, CTPV_NM, SGG_NM, EMD_NM, UGWTR_USG, DKPP_YN,
    DPH_VL, DGG_CALBR, PUMP_HRSPW, PUB_PRVTEST_SE, LINK_STATUS
) VALUES (
    s.OBJECTID, 'DR-119-1004', '제주특별자치도', '서귀포시', '안덕면', '농업용수', 'N',
    75, 140, 4, '2', 'PENDING'
);
COMMIT;

-- 6. k1m 에 접근 권한 부여
GRANT SELECT, INSERT, UPDATE, DELETE ON WT_DREAM_PERMWELL_PUBLIC_21033 TO K1M;

-- 최종 상태 확인
SELECT LINK_STATUS, COUNT(*) FROM WT_DREAM_PERMWELL_PUBLIC_21033 GROUP BY LINK_STATUS;
SELECT OBJECTID, PRMSN_DCLR_NO, CTPV_NM, SGG_NM, LINK_STATUS FROM WT_DREAM_PERMWELL_PUBLIC_21033 ORDER BY OBJECTID;
