-- ──────────────────────────────────────────────────────────────────
-- IF_SND PG sn 컬럼 IDENTITY 정합화 (2026-04-30)
-- 베이스: dev_plan/2026_04/30/if-entity-auto-increment-standardization.md
--
-- 룰: target IF entity PK = 자동채번 명시 표준
-- 4/23 default ["id","sn"] 변경의 사각지대 (others sn PK IF_SND 6 테이블) 정합화
--
-- 영향 6 테이블 (PG dev DB, others 모듈 IF_SND):
--   if_snd_tm_gd010310 (yaksoter 제원)
--   if_snd_td_gd010310 (yaksoter 수질)
--   if_snd_tm_gd014000 (nara)
--   if_snd_tm_gd014001 (news)
--   if_snd_use_legacy_data
--   if_snd_use_status_data
--
-- 옛 데이터 보호: 각 테이블 max(sn)+1 부터 sequence 시작 (충돌 방지)
-- ──────────────────────────────────────────────────────────────────

\echo '== 약수터 제원 (row 0, start 1) =='
ALTER TABLE if_snd_tm_gd010310 ALTER COLUMN sn ADD GENERATED BY DEFAULT AS IDENTITY;

\echo '== 약수터 수질 (row 0, start 1) =='
ALTER TABLE if_snd_td_gd010310 ALTER COLUMN sn ADD GENERATED BY DEFAULT AS IDENTITY;

\echo '== nara (row 22204, max 28198, start 28199) =='
ALTER TABLE if_snd_tm_gd014000 ALTER COLUMN sn ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('if_snd_tm_gd014000', 'sn'),
              GREATEST((SELECT MAX(sn) FROM if_snd_tm_gd014000), 0) + 1);

\echo '== news (row 381, max 11308, start 11309) =='
ALTER TABLE if_snd_tm_gd014001 ALTER COLUMN sn ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('if_snd_tm_gd014001', 'sn'),
              GREATEST((SELECT MAX(sn) FROM if_snd_tm_gd014001), 0) + 1);

\echo '== use_legacy (row 10, max 141707368, start 141707369) =='
ALTER TABLE if_snd_use_legacy_data ALTER COLUMN sn ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('if_snd_use_legacy_data', 'sn'),
              GREATEST((SELECT MAX(sn) FROM if_snd_use_legacy_data), 0) + 1);

\echo '== use_status (row 5, max 1005, start 1006) =='
ALTER TABLE if_snd_use_status_data ALTER COLUMN sn ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('if_snd_use_status_data', 'sn'),
              GREATEST((SELECT MAX(sn) FROM if_snd_use_status_data), 0) + 1);

\echo '== 검증 =='
SELECT table_name, column_name, is_nullable, column_default, is_identity
FROM information_schema.columns
WHERE table_name IN ('if_snd_tm_gd010310','if_snd_td_gd010310',
                     'if_snd_tm_gd014000','if_snd_tm_gd014001',
                     'if_snd_use_legacy_data','if_snd_use_status_data')
  AND column_name = 'sn'
ORDER BY table_name;
