agent-code: dmz-bojo-snd
type: SND
jewon:
  source-table: sec_jewon
  target-table: if_snd_sec_jewon
  primary-key: id
  conflict-key: source_refs
  full-copy: true
obsvdata:
  source-table: sec_obsvdata
  target-table: if_snd_sec_obsvdata
  primary-key: id
  conflict-key: source_refs
  date-column: obsv_date
  time-column: obsv_time
table-mappings:
  - name: jewon
    source: [sec_jewon]
    target: [if_snd_sec_jewon]
  - name: obsvdata
    source: [sec_obsvdata]
    target: [if_snd_sec_obsvdata]
