agent-code: dmz-bojo-loader
type: LOADER
if-table:
  jewon: if_rsv_sec_jewon
  obsvdata: if_rsv_sec_obsvdata
target-table:
  jewon: sec_jewon
  obsvdata: sec_obsvdata
step:
  batch-size: 1000
table-mappings:
  - name: jewon
    source: [if_rsv_sec_jewon]
    target: [sec_jewon]
  - name: obsvdata
    source: [if_rsv_sec_obsvdata]
    target: [sec_obsvdata]

