set pages 100 lines 200 feedback off
VARIABLE gennum   VARCHAR2(20);
VARIABLE bd       VARCHAR2(8);
VARIABLE ed       VARCHAR2(8);
EXEC :gennum := '90001';
EXEC :bd     := TO_CHAR(SYSDATE, 'YYYYMMDD');
EXEC :ed     := TO_CHAR(SYSDATE, 'YYYYMMDD');

PROMPT === datatype=1 (QLT_ID=1) ===
SELECT TAG_CN AS GENNUM, TO_CHAR(OBSRVN_DT,'YYYYMMDDHH24') YMD,
       TRUNC("5", 2) AS ELEV,
       TRUNC("163", 1) WTEMP,
       ROUND((SELECT ALTD_VL FROM TM_GD120001 WHERE GWEL_NO = TO_NUMBER(:gennum)) - "5", 2) AS LEV,
       "52" AS EC
FROM (
  SELECT * FROM (
    SELECT OBSRVN_DATA_VL, OBSRVN_DT, OBSRVN_ARTCL_ID, B.BRNCH_ID, B.TAG_CN
    FROM   PM_GD970201 A,
           (SELECT RSLT_ID, TAG_CN, OBSRVN_ARTCL_ID, BRNCH_ID
            FROM   TM_GD970101
            WHERE  HR_UNIT_ID = 3 AND TAG_CN = :gennum) B
    WHERE  A.RSLT_ID = B.RSLT_ID
    AND    OBSRVN_DT BETWEEN TO_DATE(:bd||'00','YYYYMMDDHH24') AND TO_DATE(:ed||'23','YYYYMMDDHH24')
    AND    A.QLT_ID = 1
  ) PIVOT (MAX(OBSRVN_DATA_VL) FOR OBSRVN_ARTCL_ID IN (5, 163, 52, 333))
) RR
ORDER BY YMD;
EXIT;
