set pages 100 lines 200 feedback off
SELECT * FROM (
  SELECT CTPV_NM AS SIDO, '총계' AS SIGUNGU, EXMN_YR AS YEAR, CYCL AS ODR,
         COUNT(*) AS TOTAL, COUNT(yn) AS COMPLT, COUNT(*) - COUNT(yn) AS NCOMPLT
  FROM (
    SELECT BRNCH_NM, CTPV_NM, EXMN_YR, CYCL,
           CASE WHEN TEST IS NOT NULL THEN 1 ELSE NULL END AS yn
    FROM (
      SELECT DISTINCT * FROM (
        SELECT A.GWEL_NO, A.BRNCH_NM, A.GRNDS_GWEL_NO, A.CTPV_NM,
               SUBSTR(A.STDG_CD, 0, 2) STDG_CD,
               B.WQ_INSP_SN, B.EXMN_YR, B.CYCL, B.CFMTN_YMD
        FROM   TM_GD120001 A JOIN TM_GD110301 B ON A.GWEL_NO = B.GWEL_NO
        WHERE  A.UGWTR_EXMN_CD = '215'
        AND    B.EXMN_YR = TO_CHAR(SYSDATE, 'YYYY')
        AND    A.STDG_CD LIKE '30%'
      ) TB1 LEFT JOIN (
        SELECT B.WQ_INSP_SN AS TEST
        FROM   TM_GD110301 A, TM_GD110302 B
        WHERE  A.WQ_INSP_SN = B.WQ_INSP_SN
      ) TB2 ON TB1.WQ_INSP_SN = TB2.TEST
    )
  )
  GROUP BY CTPV_NM, EXMN_YR, CYCL
  UNION ALL
  SELECT '대전광역시' AS SIDO,
         SUBSTR(BRNCH_NM, 1, 2) || DECODE(SUBSTR(SUBSTR(BRNCH_NM,1,2), -1), '구', '', '구') AS SIGUNGU,
         EXMN_YR AS YEAR, CYCL AS ODR,
         COUNT(*) AS TOTAL, COUNT(yn) AS COMPLT, COUNT(*) - COUNT(yn) AS NCOMPLT
  FROM (
    SELECT BRNCH_NM, EXMN_YR, CYCL,
           CASE WHEN TEST IS NOT NULL THEN 1 ELSE NULL END AS yn
    FROM (
      SELECT DISTINCT * FROM (
        SELECT A.GWEL_NO, A.BRNCH_NM, A.GRNDS_GWEL_NO, A.CTPV_NM,
               SUBSTR(A.STDG_CD, 0, 2) STDG_CD,
               B.WQ_INSP_SN, B.EXMN_YR, B.CYCL, B.CFMTN_YMD
        FROM   TM_GD120001 A JOIN TM_GD110301 B ON A.GWEL_NO = B.GWEL_NO
        WHERE  A.UGWTR_EXMN_CD = '215'
        AND    B.EXMN_YR = TO_CHAR(SYSDATE, 'YYYY')
        AND    A.STDG_CD LIKE '30%'
      ) TB1 LEFT JOIN (
        SELECT B.WQ_INSP_SN AS TEST
        FROM   TM_GD110301 A, TM_GD110302 B
        WHERE  A.WQ_INSP_SN = B.WQ_INSP_SN
      ) TB2 ON TB1.WQ_INSP_SN = TB2.TEST
    )
  )
  GROUP BY SUBSTR(BRNCH_NM, 1, 2), EXMN_YR, CYCL
)
ORDER BY ODR DESC,
  CASE SIGUNGU
    WHEN '총계' THEN 1
    WHEN '동구' THEN 2
    WHEN '중구' THEN 3
    WHEN '서구' THEN 4
    WHEN '유성구' THEN 5
    WHEN '대덕구' THEN 6
  END;
EXIT;
