set pages 100 lines 200 feedback off
VARIABLE gennum    VARCHAR2(20);
VARIABLE bd       VARCHAR2(8);
VARIABLE ed       VARCHAR2(8);
EXEC :gennum := '90001';
EXEC :bd     := TO_CHAR(SYSDATE-7, 'YYYYMMDD');
EXEC :ed     := TO_CHAR(SYSDATE+1, 'YYYYMMDD');

WITH TB AS (
  SELECT GWEL_NO AS GENNUM,
         TO_CHAR(OBSRVN_DT, 'YYYYMMDD') YMD,
         "5" AS ELEV,
         "163" AS WTEMP,
         ROUND((SELECT ALTD_VL FROM TM_GD120001 WHERE GWEL_NO = TO_NUMBER(:gennum)) - "5", 2) AS LEV,
         "52" AS EC
  FROM (
    SELECT * FROM (
      SELECT OBSRVN_DATA_VL, OBSRVN_DT, OBSRVN_ARTCL_ID, B.BRNCH_ID, TAG_CN AS GWEL_NO
      FROM   PM_GD970201 A,
             (SELECT RSLT_ID, TAG_CN, OBSRVN_ARTCL_ID, BRNCH_ID
              FROM TM_GD970101
              WHERE HR_UNIT_ID = 4 AND TAG_CN = :gennum) B
      WHERE  A.RSLT_ID = B.RSLT_ID
      AND    OBSRVN_DT BETWEEN TO_DATE(TO_CHAR(SYSDATE,'YYYY')-1||'0101','YYYYMMDD') AND TO_DATE(TO_CHAR(SYSDATE,'YYYY')||'1231','YYYYMMDD')
      AND    A.QLT_ID = 1
    )
    PIVOT (MAX(OBSRVN_DATA_VL) FOR OBSRVN_ARTCL_ID IN (5, 163, 52, 333))
  ) RR
  UNION
  SELECT GWEL_NO AS GENNUM,
         TO_CHAR(OBSRVN_DT, 'YYYYMMDD') YMD,
         "5" AS ELEV,
         "163" AS WTEMP,
         ROUND((SELECT ALTD_VL FROM TM_GD120001 WHERE GWEL_NO = TO_NUMBER(:gennum)) - "5", 2) AS LEV,
         "52" AS EC
  FROM (
    SELECT * FROM (
      SELECT OBSRVN_DATA_VL, OBSRVN_DT, OBSRVN_ARTCL_ID, B.BRNCH_ID, TAG_CN AS GWEL_NO
      FROM   PM_GD970201 A,
             (SELECT RSLT_ID, TAG_CN, OBSRVN_ARTCL_ID, BRNCH_ID
              FROM TM_GD970101
              WHERE HR_UNIT_ID = 4 AND TAG_CN = :gennum) B
      WHERE  A.RSLT_ID = B.RSLT_ID
      AND    OBSRVN_DT BETWEEN TO_DATE('19951201','YYYYMMDD') AND TO_DATE(TO_CHAR(SYSDATE,'YYYY')-2||'1231','YYYYMMDD')
      AND    A.QLT_ID = 5
    )
    PIVOT (MAX(OBSRVN_DATA_VL) FOR OBSRVN_ARTCL_ID IN (5, 163, 52, 333))
  ) RR
)
SELECT * FROM TB
WHERE YMD BETWEEN :bd AND :ed
ORDER BY YMD ASC;
EXIT;
