-- saeol-tibero sync_log
-- 2026-05-19 — sync_log = agent.target 룰 일관 통용
-- 새올 SND (target=saeol-oracle) 의 sync_log 적재 위치 = 자기 target.
-- Internal Oracle / dev PG sync_log 와 컬럼 양식 정합 (entity: SyncLog.java).
-- 운영 Tibero 적용은 새올 DBA 협의 별 트랙.

CREATE TABLE sync_log (
    id                 NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE,
    execution_id       VARCHAR2(100) NOT NULL,
    step_id            VARCHAR2(50),
    mapping_name       VARCHAR2(100),
    source_tables      VARCHAR2(4000),
    target_tables      VARCHAR2(4000),
    source_pk_column   VARCHAR2(100),
    read_count         NUMBER,
    write_count        NUMBER,
    failed_count       NUMBER,
    skip_count         NUMBER,
    failed_keys        VARCHAR2(4000),
    error_summary      VARCHAR2(4000),
    created_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_sync_log PRIMARY KEY (id)
);

CREATE INDEX idx_sync_log_execution ON sync_log (execution_id);
CREATE INDEX idx_sync_log_mapping   ON sync_log (execution_id, mapping_name);
