"""
Oracle DDL 백업 파일을 파싱하여 JPA Entity Java 파일을 생성하는 스크립트.
사용: python scripts/gen_entities.py
"""
import re
import os

DDL_FILE = "scripts/ddl/internal-oracle/original-ddl-backup.sql"
BASE_DIR = "sync-agent-bojo-int/src/main/java/com/sync/agent/bojoint/entity"
PACKAGE_BASE = "com.sync.agent.bojoint.entity"

# 테이블 분류
IF_RSV_SAEOL_TABLES = {
    "IF_RSV_RGETHKMIR01", "IF_RSV_RGETNJHMS01", "IF_RSV_RGETNKCNO01",
    "IF_RSV_RGETNKMTB01", "IF_RSV_RGETNMNFE01", "IF_RSV_RGETNOPMS01",
    "IF_RSV_RGETNPMMS01", "IF_RSV_RGETNSCKT01", "IF_RSV_RGETNSIMS01",
    "IF_RSV_RGETNTGMS02", "IF_RSV_RGETNWAMS01", "IF_RSV_RGETNWAVI05",
    "IF_RSV_RGETNWAVI06", "IF_RSV_RGETNYCSG01", "IF_RSV_RGETNYYMS01",
    "IF_RSV_RGETSTGMS01",
}

IF_RSV_OTHER_TABLES = {
    "IF_RSV_SEC_JEWON", "IF_RSV_SEC_OBSVDATA",
    "IF_RSV_TB_JEJU_JEWON", "IF_RSV_TB_JEJU",
    "IF_RSV_USE_LEGACY_DATA", "IF_RSV_USE_STATUS_DATA",
    "IF_RSV_USE_JEJU_DAY",
}

SOURCE_SAEOL_TABLES = {
    "RGETHKMIR01", "RGETNJHMS01", "RGETNKCNO01", "RGETNKMTB01",
    "RGETNMNFE01", "RGETNOPMS01", "RGETNPMMS01", "RGETNSCKT01",
    "RGETNSIMS01", "RGETNTGMS02", "RGETNWAMS01", "RGETNWAVI05",
    "RGETNWAVI06", "RGETNYCSG01", "RGETNYYMS01", "RGETSTGMS01",
}

TARGET_TABLES = {
    "TM_GD970001", "TM_GD120001", "TM_GD970130", "TM_GD970002",
    "TM_GD970101", "TM_GD980002",
    "PM_GD970201", "PM_GD970202",
    "TM_GD111010", "PM_GD111021", "PM_GD111022",
    "TM_GD111024", "TM_GD111025",
}

SKIP_TABLES = {"EXECUTION", "SYNC_LOG"}  # common 모듈에 이미 있음

# Oracle 타입 → Java 타입 매핑
def oracle_to_java_type(oracle_type, col_name):
    t = oracle_type.upper().strip()
    if t.startswith("NUMBER") or t == "NUMBER":
        # IDENTITY PK → Long
        if "GENERATED BY DEFAULT AS IDENTITY" in oracle_type:
            return "Long"
        # NUMBER(p,s) with s > 0 → BigDecimal
        m = re.match(r"NUMBER\((\d+),(\d+)\)", t)
        if m and int(m.group(2)) > 0:
            return "java.math.BigDecimal"
        m2 = re.match(r"NUMBER\((\d+)\)", t)
        if m2:
            p = int(m2.group(1))
            if p <= 9:
                return "Integer"
            return "Long"
        return "Long"
    elif t.startswith("VARCHAR2") or t.startswith("VARCHAR"):
        return "String"
    elif t.startswith("CHAR"):
        return "String"
    elif t == "DATE":
        return "java.time.LocalDateTime"
    elif t.startswith("TIMESTAMP"):
        return "java.time.LocalDateTime"
    elif t.startswith("CLOB") or t == "LONG":
        return "String"
    else:
        return "String"


def table_name_to_class_name(table_name):
    """테이블명 → Java 클래스명"""
    # IF_RSV_RGETHKMIR01 → IfRsvRgethkmir01
    # TM_GD970001 → TmGd970001
    # PM_GD970201 → PmGd970201
    parts = table_name.split("_")
    result = ""
    for part in parts:
        if part:
            result += part[0].upper() + part[1:].lower()
    return result


def column_name_to_field_name(col_name):
    """컬럼명 → Java 필드명 (camelCase)"""
    parts = col_name.lower().split("_")
    result = parts[0]
    for part in parts[1:]:
        if part:
            result += part[0].upper() + part[1:]
    return result


def get_subpackage(table_name):
    if table_name in IF_RSV_SAEOL_TABLES:
        return "iftable.saeol"
    elif table_name in IF_RSV_OTHER_TABLES:
        return "iftable"
    elif table_name in SOURCE_SAEOL_TABLES:
        return "source"
    elif table_name in TARGET_TABLES:
        return "target"
    else:
        return None


def parse_ddl(ddl_content):
    """DDL 텍스트에서 테이블 정의를 파싱"""
    tables = {}
    # CREATE TABLE "K1M"."TABLE_NAME" 패턴으로 분리
    pattern = r'CREATE TABLE "K1M"\."(\w+)"\s*\((.*?)\)\s*$'
    blocks = re.split(r'\n\s*\n', ddl_content)

    for block in blocks:
        block = block.strip()
        m = re.match(r'\s*CREATE TABLE "K1M"\."(\w+)"\s*\((.+)', block, re.DOTALL)
        if not m:
            continue
        table_name = m.group(1)
        body = m.group(2)

        columns = []
        constraints = []
        is_identity = {}
        not_null_cols = set()

        for line in body.split("\n"):
            line = line.strip().rstrip(",")
            if not line:
                continue

            # CONSTRAINT 라인
            if line.startswith("CONSTRAINT") or line.startswith("USING INDEX"):
                if "PRIMARY KEY" in line:
                    pk_match = re.search(r'PRIMARY KEY \((.+?)\)', line)
                    if pk_match:
                        pk_cols = [c.strip().strip('"') for c in pk_match.group(1).split(",")]
                        constraints.append(("PK", pk_cols))
                elif "UNIQUE" in line:
                    uk_match = re.search(r'UNIQUE \((.+?)\)', line)
                    if uk_match:
                        uk_cols = [c.strip().strip('"') for c in uk_match.group(1).split(",")]
                        constraints.append(("UK", uk_cols))
                continue

            # 컬럼 정의
            col_match = re.match(r'"(\w+)"\s+(.+)', line)
            if col_match:
                col_name = col_match.group(1)
                col_def = col_match.group(2)

                # IDENTITY 감지
                if "GENERATED BY DEFAULT AS IDENTITY" in col_def:
                    is_identity[col_name] = True

                # NOT NULL 감지
                if "NOT NULL" in col_def:
                    not_null_cols.add(col_name)

                # 타입 추출
                type_match = re.match(r'((?:NUMBER|VARCHAR2|VARCHAR|CHAR|DATE|TIMESTAMP|CLOB|LONG)(?:\([^)]*\))?)', col_def)
                if type_match:
                    oracle_type = type_match.group(1)
                    if col_name in is_identity:
                        oracle_type = "GENERATED BY DEFAULT AS IDENTITY " + oracle_type
                else:
                    oracle_type = "VARCHAR2(255)"

                # 길이 추출
                length_match = re.match(r'(?:VARCHAR2|VARCHAR|CHAR)\((\d+)\)', oracle_type)
                length = int(length_match.group(1)) if length_match else None

                columns.append({
                    "name": col_name,
                    "oracle_type": oracle_type,
                    "java_type": oracle_to_java_type(oracle_type, col_name),
                    "length": length,
                    "not_null": col_name in not_null_cols,
                    "identity": col_name in is_identity,
                })

        pk_cols = []
        for ctype, ccols in constraints:
            if ctype == "PK":
                pk_cols = ccols

        tables[table_name] = {
            "columns": columns,
            "pk_cols": pk_cols,
            "constraints": constraints,
        }

    return tables


def generate_entity(table_name, table_info, subpackage):
    """Java Entity 소스코드 생성"""
    class_name = table_name_to_class_name(table_name)
    package = f"{PACKAGE_BASE}.{subpackage}"
    pk_cols = table_info["pk_cols"]
    columns = table_info["columns"]

    # IF 공통 컬럼 (builder default)
    if_common_cols = {"LINK_STATUS", "EXTRACTED_AT"}

    imports = set()
    imports.add("import javax.persistence.*;")
    imports.add("import lombok.*;")

    needs_big_decimal = any(c["java_type"] == "java.math.BigDecimal" for c in columns)
    needs_local_datetime = any(c["java_type"] == "java.time.LocalDateTime" for c in columns)

    if needs_big_decimal:
        imports.add("import java.math.BigDecimal;")
    if needs_local_datetime:
        imports.add("import java.time.LocalDateTime;")

    # 복합 PK 여부
    composite_pk = len(pk_cols) > 1

    lines = []
    lines.append(f"package {package};")
    lines.append("")
    for imp in sorted(imports):
        lines.append(imp)
    lines.append("")

    # 클래스 어노테이션
    lines.append(f'@Entity')
    lines.append(f'@Table(name = "{table_name}")')
    lines.append("@Getter")
    lines.append("@Setter")
    lines.append("@NoArgsConstructor")
    lines.append("@AllArgsConstructor")
    lines.append("@Builder")

    if composite_pk:
        id_class_name = class_name + "Id"
        lines.append(f"@IdClass({id_class_name}.class)")

    lines.append(f"public class {class_name} {{")
    lines.append("")

    for col in columns:
        col_name = col["name"]
        field_name = column_name_to_field_name(col_name)
        java_type = col["java_type"]

        # 타입 간소화
        if java_type == "java.math.BigDecimal":
            java_type = "BigDecimal"
        elif java_type == "java.time.LocalDateTime":
            java_type = "LocalDateTime"

        annotations = []

        # PK
        if col_name in pk_cols:
            annotations.append("    @Id")
            if col["identity"] and not composite_pk:
                annotations.append("    @GeneratedValue(strategy = GenerationType.IDENTITY)")

        # @Column
        col_attrs = []
        col_attrs.append(f'name = "{col_name}"')
        if col["length"] and col["length"] != 255:
            col_attrs.append(f'length = {col["length"]}')
        if col["not_null"] and col_name not in pk_cols:
            col_attrs.append("nullable = false")

        col_annotation = f'    @Column({", ".join(col_attrs)})'
        annotations.append(col_annotation)

        # Builder.Default for LINK_STATUS
        default_val = None
        if col_name == "LINK_STATUS":
            default_val = '"PENDING"'

        for ann in annotations:
            lines.append(ann)

        if default_val:
            lines.append("    @Builder.Default")
            lines.append(f"    private {java_type} {field_name} = {default_val};")
        else:
            lines.append(f"    private {java_type} {field_name};")
        lines.append("")

    lines.append("}")
    lines.append("")

    # 복합키 IdClass 생성
    id_class_content = None
    if composite_pk:
        id_lines = []
        id_lines.append(f"package {package};")
        id_lines.append("")
        id_lines.append("import lombok.*;")
        id_lines.append("import java.io.Serializable;")
        id_lines.append("")
        id_lines.append("@Getter")
        id_lines.append("@Setter")
        id_lines.append("@NoArgsConstructor")
        id_lines.append("@AllArgsConstructor")
        id_lines.append("@EqualsAndHashCode")
        id_lines.append(f"public class {id_class_name} implements Serializable {{")
        id_lines.append("")
        for pk_col in pk_cols:
            pk_field = column_name_to_field_name(pk_col)
            # PK 컬럼의 타입 찾기
            pk_type = "Long"
            for c in columns:
                if c["name"] == pk_col:
                    t = c["java_type"]
                    if t == "java.math.BigDecimal":
                        t = "BigDecimal"
                        id_lines.insert(3, "import java.math.BigDecimal;")
                    elif t == "java.time.LocalDateTime":
                        t = "LocalDateTime"
                        id_lines.insert(3, "import java.time.LocalDateTime;")
                    pk_type = t
                    break
            id_lines.append(f"    private {pk_type} {pk_field};")
        id_lines.append("")
        id_lines.append("}")
        id_lines.append("")
        id_class_content = "\n".join(id_lines)

    return "\n".join(lines), id_class_content


def main():
    with open(DDL_FILE, "r", encoding="utf-8") as f:
        ddl_content = f.read()

    tables = parse_ddl(ddl_content)
    print(f"파싱된 테이블: {len(tables)}개")

    generated = 0
    skipped = 0

    for table_name, table_info in sorted(tables.items()):
        if table_name in SKIP_TABLES:
            print(f"  SKIP (common): {table_name}")
            skipped += 1
            continue

        subpackage = get_subpackage(table_name)
        if subpackage is None:
            print(f"  SKIP (분류 안됨): {table_name}")
            skipped += 1
            continue

        class_name = table_name_to_class_name(table_name)
        subdir = subpackage.replace(".", "/")
        dir_path = os.path.join(BASE_DIR, subdir)
        os.makedirs(dir_path, exist_ok=True)

        entity_code, id_class_code = generate_entity(table_name, table_info, subpackage)

        file_path = os.path.join(dir_path, f"{class_name}.java")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(entity_code)
        print(f"  생성: {subpackage}.{class_name} ({len(table_info['columns'])}컬럼)")
        generated += 1

        if id_class_code:
            id_file_path = os.path.join(dir_path, f"{class_name}Id.java")
            with open(id_file_path, "w", encoding="utf-8") as f:
                f.write(id_class_code)
            print(f"  생성: {subpackage}.{class_name}Id (복합키)")
            generated += 1

    print(f"\n완료: 생성 {generated}개, 스킵 {skipped}개")


if __name__ == "__main__":
    main()
