import sys, os

meta_path = os.path.join(os.path.dirname(__file__), 'oracle_meta.txt')
tables = {}
with open(meta_path, 'r') as f:
    for line in f:
        line = line.strip()
        if not line or '|' not in line:
            continue
        parts = line.split('|')
        if len(parts) < 5:
            continue
        tbl, col, dtype, size, nullable = parts[0].strip(), parts[1].strip(), parts[2].strip(), parts[3].strip(), parts[4].strip()
        if tbl == 'LINK_PLAN':
            continue
        if tbl not in tables:
            tables[tbl] = []
        if dtype in ('VARCHAR2', 'CHAR'):
            col_def = f"{col} {dtype}({size})"
        elif dtype == 'NUMBER' and size:
            col_def = f"{col} NUMBER({size})"
        elif dtype == 'NUMBER':
            col_def = f"{col} NUMBER"
        elif dtype == 'DATE':
            col_def = f"{col} DATE"
        else:
            col_def = f"{col} {dtype}"
        tables[tbl].append(col_def)

lines = []
lines.append('-- =============================================')
lines.append('-- saeol-oracle-init.sql')
lines.append('-- Oracle 29005 (XEPDB1, K1M)')
lines.append('-- IF_SND 16 tables + LINK_PLAN_CURSOR + test data')
lines.append('-- =============================================')
lines.append('')
lines.append('-- 1. LINK_PLAN_CURSOR')
lines.append('DROP TABLE LINK_PLAN_CURSOR CASCADE CONSTRAINTS;')
lines.append('CREATE TABLE LINK_PLAN_CURSOR (')
lines.append('    AGENT_CODE VARCHAR2(50) PRIMARY KEY,')
lines.append('    LAST_LINK_IDX NUMBER DEFAULT 0 NOT NULL,')
lines.append('    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP')
lines.append(');')
lines.append('')
lines.append('-- 2. IF_SND tables (16)')

for tbl in sorted(tables.keys()):
    cols = tables[tbl]
    if_tbl = f'IF_SND_{tbl}'
    lines.append('')
    lines.append(f'DROP TABLE {if_tbl} CASCADE CONSTRAINTS;')
    lines.append(f'CREATE TABLE {if_tbl} (')
    lines.append(f'    ID NUMBER GENERATED BY DEFAULT AS IDENTITY,')
    for col_def in cols:
        lines.append(f'    {col_def},')
    lines.append(f'    SOURCE_REFS VARCHAR2(4000),')
    lines.append(f'    LINK_STATUS VARCHAR2(20) DEFAULT \'PENDING\',')
    lines.append(f'    EXTRACTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,')
    lines.append(f'    UPDATED_AT TIMESTAMP,')
    lines.append(f'    EXECUTION_ID VARCHAR2(255),')
    lines.append(f'    CONSTRAINT PK_{if_tbl} PRIMARY KEY (ID),')
    lines.append(f'    CONSTRAINT UK_{if_tbl}_SR UNIQUE (SOURCE_REFS)')
    lines.append(');')
    lines.append(f'CREATE INDEX IDX_{if_tbl}_EID ON {if_tbl} (EXECUTION_ID);')

# Test data
lines.append('')
lines.append('-- 3. Test data: source tables + LINK_PLAN')
lines.append('')
lines.append('-- RGETNTGMS02 (7 cols, simple)')
lines.append("INSERT INTO RGETNTGMS02 (REL_TRANS_CGG_CODE, SF_TEAM_CODE, CRIT_YY, QW_ISP_SORT_CODE, LIST_CODE, CRIT_VALUE, FIRST_REG_DTHR)")
lines.append("VALUES ('3650000', '3650000', '2026', '1', 'PH', '6.5~8.5', SYSDATE);")
lines.append("INSERT INTO RGETNTGMS02 (REL_TRANS_CGG_CODE, SF_TEAM_CODE, CRIT_YY, QW_ISP_SORT_CODE, LIST_CODE, CRIT_VALUE, FIRST_REG_DTHR)")
lines.append("VALUES ('3650000', '3650000', '2025', '1', 'PH', '6.0~8.5', SYSDATE);")
lines.append('')
lines.append('-- RGETNPMMS01 (95 cols, max columns)')
lines.append("INSERT INTO RGETNPMMS01 (REL_TRANS_CGG_CODE, PERM_NT_NO, SF_TEAM_CODE, PERM_NT_FORM_CODE, APLR_GBN_CODE, PERM_YN, LNHO_RAISE_YN, PERM_CANCEL_YN, JGONG_DEAL_YN, FIRST_REG_DTHR)")
lines.append("VALUES ('3650000', 'A001', '3650000', '1', '01', 'Y', 'N', 'N', 'N', SYSDATE);")
lines.append("INSERT INTO RGETNPMMS01 (REL_TRANS_CGG_CODE, PERM_NT_NO, SF_TEAM_CODE, PERM_NT_FORM_CODE, APLR_GBN_CODE, PERM_YN, LNHO_RAISE_YN, PERM_CANCEL_YN, JGONG_DEAL_YN, FIRST_REG_DTHR)")
lines.append("VALUES ('3650000', 'A002', '3650000', '2', '02', 'Y', 'N', 'N', 'Y', SYSDATE);")
lines.append('')
lines.append('-- RGETNOPMS01 (partial PK in LINK_PLAN)')
lines.append("INSERT INTO RGETNOPMS01 (REL_TRANS_CGG_CODE, PERM_NT_NO, JGONG_NT_SNO, APPL_DOC_GBN_CODE, FIRST_REG_DTHR)")
lines.append("VALUES ('3650000', 'A001', 1, '01', SYSDATE);")
lines.append("INSERT INTO RGETNOPMS01 (REL_TRANS_CGG_CODE, PERM_NT_NO, JGONG_NT_SNO, APPL_DOC_GBN_CODE, FIRST_REG_DTHR)")
lines.append("VALUES ('3650000', 'A001', 2, '02', SYSDATE);")
lines.append('')
lines.append('-- LINK_PLAN events')
lines.append("DELETE FROM LINK_PLAN;")
lines.append("INSERT INTO LINK_PLAN (LINK_IDX, TABLE_NAME, FLAG, SF_TEAM_CODE, PERM_NT_NO, REG_DATE)")
lines.append("VALUES (1, 'RGETNTGMS02', 'I', '3650000', NULL, SYSDATE);")
lines.append("INSERT INTO LINK_PLAN (LINK_IDX, TABLE_NAME, FLAG, SF_TEAM_CODE, PERM_NT_NO, YY_GBN, REG_DATE)")
lines.append("VALUES (2, 'RGETNTGMS02', 'U', '3650000', NULL, '2025', SYSDATE);")
lines.append("INSERT INTO LINK_PLAN (LINK_IDX, TABLE_NAME, FLAG, SF_TEAM_CODE, PERM_NT_NO, REG_DATE)")
lines.append("VALUES (3, 'RGETNPMMS01', 'I', '3650000', 'A001', SYSDATE);")
lines.append("INSERT INTO LINK_PLAN (LINK_IDX, TABLE_NAME, FLAG, SF_TEAM_CODE, PERM_NT_NO, REG_DATE)")
lines.append("VALUES (4, 'RGETNPMMS01', 'U', '3650000', 'A001', SYSDATE);")
lines.append("INSERT INTO LINK_PLAN (LINK_IDX, TABLE_NAME, FLAG, SF_TEAM_CODE, PERM_NT_NO, REG_DATE)")
lines.append("VALUES (5, 'RGETNPMMS01', 'I', '3650000', 'A002', SYSDATE);")
lines.append("INSERT INTO LINK_PLAN (LINK_IDX, TABLE_NAME, FLAG, SF_TEAM_CODE, PERM_NT_NO, REG_DATE)")
lines.append("VALUES (6, 'RGETNOPMS01', 'I', '3650000', 'A001', SYSDATE);")
lines.append('')
lines.append('COMMIT;')

output_path = os.path.join(os.path.dirname(__file__), 'saeol-oracle-init.sql')
with open(output_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print(f"Generated {len(lines)} lines to {output_path}")
print(f"Tables: {len(tables)}")
