import os

meta_path = os.path.join(os.path.dirname(__file__), 'oracle_meta.txt')
tables = {}
with open(meta_path, 'r') as f:
    for line in f:
        line = line.strip()
        if not line or '|' not in line:
            continue
        parts = line.split('|')
        if len(parts) < 5:
            continue
        tbl, col, dtype, size, nullable = [p.strip() for p in parts]
        if tbl == 'LINK_PLAN':
            continue
        if tbl not in tables:
            tables[tbl] = []
        if dtype in ('VARCHAR2', 'CHAR'):
            col_def = f"{col} {dtype}({size})"
        elif dtype == 'NUMBER' and size:
            col_def = f"{col} NUMBER({size})"
        elif dtype == 'NUMBER':
            col_def = f"{col} NUMBER"
        elif dtype == 'DATE':
            col_def = f"{col} DATE"
        else:
            col_def = f"{col} {dtype}"
        tables[tbl].append(col_def)

lines = []
lines.append('-- =============================================')
lines.append('-- 새올 Internal 파이프라인 DDL (Oracle 29004/XEPDB1)')
lines.append('-- IF_RSV 16개 + GIMS 타겟 16개')
lines.append('-- =============================================')
lines.append('')

for tbl in sorted(tables.keys()):
    cols = tables[tbl]
    
    # IF_RSV 테이블
    if_tbl = f'IF_RSV_{tbl}'
    lines.append(f'-- {if_tbl}')
    lines.append(f'CREATE TABLE {if_tbl} (')
    lines.append(f'    ID NUMBER GENERATED BY DEFAULT AS IDENTITY,')
    for col_def in cols:
        lines.append(f'    {col_def},')
    lines.append(f'    SOURCE_REFS VARCHAR2(4000),')
    lines.append(f'    LINK_STATUS VARCHAR2(20) DEFAULT \'PENDING\',')
    lines.append(f'    EXTRACTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,')
    lines.append(f'    UPDATED_AT TIMESTAMP,')
    lines.append(f'    EXECUTION_ID VARCHAR2(255),')
    lines.append(f'    CONSTRAINT PK_{if_tbl} PRIMARY KEY (ID),')
    lines.append(f'    CONSTRAINT UK_{if_tbl}_SR UNIQUE (SOURCE_REFS)')
    lines.append(');')
    lines.append(f'CREATE INDEX IDX_{if_tbl}_EID ON {if_tbl} (EXECUTION_ID);')
    lines.append('')

    # GIMS 타겟 테이블 (원본과 동일 이름)
    # 29004에 원본 이름이 이미 있으면 충돌하므로 확인 필요
    # 새올 테이블은 29004에 없으므로 안전
    lines.append(f'-- {tbl} (GIMS 타겟)')
    lines.append(f'CREATE TABLE {tbl} (')
    lines.append(f'    ID NUMBER GENERATED BY DEFAULT AS IDENTITY,')
    for col_def in cols:
        lines.append(f'    {col_def},')
    lines.append(f'    SOURCE_REFS VARCHAR2(4000),')
    lines.append(f'    LINK_STATUS VARCHAR2(20) DEFAULT \'PENDING\',')
    lines.append(f'    EXTRACTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,')
    lines.append(f'    UPDATED_AT TIMESTAMP,')
    lines.append(f'    EXECUTION_ID VARCHAR2(255),')
    lines.append(f'    CONSTRAINT PK_GIMS_{tbl} PRIMARY KEY (ID),')
    lines.append(f'    CONSTRAINT UK_GIMS_{tbl}_SR UNIQUE (SOURCE_REFS)')
    lines.append(');')
    lines.append(f'CREATE INDEX IDX_GIMS_{tbl}_EID ON {tbl} (EXECUTION_ID);')
    lines.append('')

output_path = os.path.join(os.path.dirname(__file__), 'oracle-init-internal-saeol.sql')
with open(output_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print(f"Generated {len(lines)} lines, {len(tables)} tables x 2 = {len(tables)*2} DDL")
