-- ============================================================
-- IF 테이블 DDL (Oracle XE 21c: k1m@XEPDB1)
-- 내부망 RCV가 적재하는 IF_RSV 테이블
-- PG JPA 엔티티(IfRsvSecJewon, IfRsvSecObsvdata) 기반 Oracle 변환
-- ============================================================

-- 1. IF 수신 제원
CREATE TABLE IF_RSV_SEC_JEWON (
    ID             NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OBSV_CODE      VARCHAR2(255) NOT NULL,
    OBSV_NAME      VARCHAR2(255),
    WELL           NUMBER(10),
    SIDO           VARCHAR2(255),
    SIGUNGU        VARCHAR2(255),
    UPMYUNDO       VARCHAR2(255),
    BUNJI          VARCHAR2(255),
    RI             VARCHAR2(255),
    X              VARCHAR2(255),
    Y              VARCHAR2(255),
    PYOGO          NUMBER,
    INSDATE        DATE,
    GULDEP         NUMBER,
    GULDIA         NUMBER,
    REGDATE        DATE,
    CASING_HEIGHT  NUMBER,
    SOURCE_REFS    VARCHAR2(4000) NOT NULL,
    LINK_STATUS    VARCHAR2(20) DEFAULT 'PENDING',
    EXTRACTED_AT   TIMESTAMP,
    UPDATED_AT     TIMESTAMP,
    EXECUTION_ID   VARCHAR2(255),
    CONSTRAINT UK_IF_RSV_JEWON_SREFS UNIQUE (SOURCE_REFS)
);

CREATE INDEX IDX_IF_RSV_JEWON_EXEC ON IF_RSV_SEC_JEWON (EXECUTION_ID);

-- 2. IF 수신 관측데이터
CREATE TABLE IF_RSV_SEC_OBSVDATA (
    ID             NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OBSV_CODE      VARCHAR2(255) NOT NULL,
    OBSV_DATE      DATE NOT NULL,
    OBSV_TIME      VARCHAR2(8),
    GWDEP          NUMBER,
    GWTEMP         NUMBER,
    EC             NUMBER,
    REMARK         VARCHAR2(255),
    SOURCE_REFS    VARCHAR2(4000) NOT NULL,
    LINK_STATUS    VARCHAR2(20) DEFAULT 'PENDING',
    EXTRACTED_AT   TIMESTAMP,
    UPDATED_AT     TIMESTAMP,
    EXECUTION_ID   VARCHAR2(255),
    CONSTRAINT UK_IF_RSV_OBSV_SREFS UNIQUE (SOURCE_REFS)
);

CREATE INDEX IDX_IF_RSV_OBSV_EXEC ON IF_RSV_SEC_OBSVDATA (EXECUTION_ID);

-- ============================================================
-- 확인용
-- ============================================================
SELECT table_name FROM user_tables ORDER BY table_name;
