-- ============================================================
-- 이용량 Loader Target 테이블 DDL (Oracle 29004)
-- I5(UseLoadStep)이 적재하는 타겟 테이블 (4개)
-- + TM_GD111010 (이용량시설) — I3에서 본격 사용, I5에서 BRNCH_ID 조회용
-- 실행: docker exec -i gims_orchestrator_inner_oracle sqlplus k1m/1111@//localhost:1521/XEPDB1 < scripts/oracle-init-use-target.sql
-- ============================================================

-- ============================================================
-- 0. TM_GD111010 (이용량시설) — BRNCH_ID 조회 마스터
--    I3(JejuFacilityLoadStep)에서 전체 컬럼 INSERT 예정
--    여기서는 I5 필수 컬럼만 선행 생성
-- ============================================================
CREATE TABLE TM_GD111010 (
    BRNCH_ID                    NUMBER(22)     GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TELNO                       VARCHAR2(100),
    EXECUTION_ID                VARCHAR2(255),
    SOURCE_REFS                 VARCHAR2(4000),
    CONSTRAINT PK_TM_GD111010 PRIMARY KEY (BRNCH_ID)
);

COMMENT ON TABLE TM_GD111010 IS '이용량시설';
COMMENT ON COLUMN TM_GD111010.BRNCH_ID IS '지점아이디';
COMMENT ON COLUMN TM_GD111010.TELNO IS '전화번호';
COMMENT ON COLUMN TM_GD111010.EXECUTION_ID IS '실행ID(추적용)';
COMMENT ON COLUMN TM_GD111010.SOURCE_REFS IS '소스참조(추적용)';

CREATE INDEX IDX_TM_GD111010_TELNO ON TM_GD111010(TELNO);
CREATE INDEX IDX_TM_GD111010_EID ON TM_GD111010(EXECUTION_ID);

-- ============================================================
-- 1. PM_GD111021 (이용량시간자료)
-- ============================================================
CREATE TABLE PM_GD111021 (
    BRNCH_ID                    NUMBER(22)     NOT NULL,
    OBSRVN_DT                   DATE           NOT NULL,
    LAST_MSRMT_VL               NUMBER(10),
    USE_QNT                     NUMBER(22),
    EXECUTION_ID                VARCHAR2(255),
    SOURCE_REFS                 VARCHAR2(4000),
    CONSTRAINT PK_PM_GD111021 PRIMARY KEY (BRNCH_ID, OBSRVN_DT)
);

COMMENT ON TABLE PM_GD111021 IS '이용량시간자료';
COMMENT ON COLUMN PM_GD111021.BRNCH_ID IS '지점아이디';
COMMENT ON COLUMN PM_GD111021.OBSRVN_DT IS '관측일시';
COMMENT ON COLUMN PM_GD111021.LAST_MSRMT_VL IS '최종측정값';
COMMENT ON COLUMN PM_GD111021.USE_QNT IS '사용량';
COMMENT ON COLUMN PM_GD111021.EXECUTION_ID IS '실행ID(추적용)';
COMMENT ON COLUMN PM_GD111021.SOURCE_REFS IS '소스참조(추적용)';

CREATE INDEX IDX_PM_GD111021_EID ON PM_GD111021(EXECUTION_ID);

-- ============================================================
-- 2. PM_GD111022 (이용량일자료) — I3과 공유
-- ============================================================
CREATE TABLE PM_GD111022 (
    BRNCH_ID                    NUMBER(22)     NOT NULL,
    OBSRVN_YMD                  VARCHAR2(8)    NOT NULL,
    LAST_MSRMT_VL               NUMBER(10),
    USE_QNT                     NUMBER(22),
    EXECUTION_ID                VARCHAR2(255),
    SOURCE_REFS                 VARCHAR2(4000),
    CONSTRAINT PK_PM_GD111022 PRIMARY KEY (BRNCH_ID, OBSRVN_YMD)
);

COMMENT ON TABLE PM_GD111022 IS '이용량일자료';
COMMENT ON COLUMN PM_GD111022.BRNCH_ID IS '지점아이디';
COMMENT ON COLUMN PM_GD111022.OBSRVN_YMD IS '관측일자';
COMMENT ON COLUMN PM_GD111022.LAST_MSRMT_VL IS '최종측정값';
COMMENT ON COLUMN PM_GD111022.USE_QNT IS '사용량';
COMMENT ON COLUMN PM_GD111022.EXECUTION_ID IS '실행ID(추적용)';
COMMENT ON COLUMN PM_GD111022.SOURCE_REFS IS '소스참조(추적용)';

CREATE INDEX IDX_PM_GD111022_EID ON PM_GD111022(EXECUTION_ID);

-- ============================================================
-- 3. TM_GD111024 (이용량최근수신현황)
-- ============================================================
CREATE TABLE TM_GD111024 (
    BRNCH_ID                    NUMBER(22)     NOT NULL,
    OBSRVN_DT                   DATE           NOT NULL,
    EXECUTION_ID                VARCHAR2(255),
    SOURCE_REFS                 VARCHAR2(4000),
    CONSTRAINT PK_TM_GD111024 PRIMARY KEY (BRNCH_ID)
);

COMMENT ON TABLE TM_GD111024 IS '이용량최근수신현황';
COMMENT ON COLUMN TM_GD111024.BRNCH_ID IS '지점아이디';
COMMENT ON COLUMN TM_GD111024.OBSRVN_DT IS '관측일시';
COMMENT ON COLUMN TM_GD111024.EXECUTION_ID IS '실행ID(추적용)';
COMMENT ON COLUMN TM_GD111024.SOURCE_REFS IS '소스참조(추적용)';

CREATE INDEX IDX_TM_GD111024_EID ON TM_GD111024(EXECUTION_ID);

-- ============================================================
-- 4. TM_GD111025 (이용량관측데이터)
-- ============================================================
CREATE TABLE TM_GD111025 (
    SN                          NUMBER(22)     NOT NULL,
    TELNO                       VARCHAR2(100),
    OBSRVN_DT                   DATE,
    LAST_CHG_DT                 DATE,
    EXECUTION_ID                VARCHAR2(255),
    SOURCE_REFS                 VARCHAR2(4000),
    CONSTRAINT PK_TM_GD111025 PRIMARY KEY (SN)
);

COMMENT ON TABLE TM_GD111025 IS '이용량관측데이터';
COMMENT ON COLUMN TM_GD111025.SN IS '일련번호';
COMMENT ON COLUMN TM_GD111025.TELNO IS '전화번호';
COMMENT ON COLUMN TM_GD111025.OBSRVN_DT IS '관측일시';
COMMENT ON COLUMN TM_GD111025.LAST_CHG_DT IS '최종변경일시';
COMMENT ON COLUMN TM_GD111025.EXECUTION_ID IS '실행ID(추적용)';
COMMENT ON COLUMN TM_GD111025.SOURCE_REFS IS '소스참조(추적용)';

CREATE INDEX IDX_TM_GD111025_EID ON TM_GD111025(EXECUTION_ID);

COMMIT;
