#!/bin/bash
# =============================================================
# 전처리 Agent 개발 환경 원클릭 셋업
# 실행: bash scripts/provide-env-setup.sh
# =============================================================
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# 색상
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[..]${NC} $1"; }
err()  { echo -e "${RED}[ERR]${NC} $1"; exit 1; }

# ----- 컨테이너/포트 설정 (기존 환경과 동일) -----
ORACLE_CONTAINER="gims_orchestrator_inner_oracle"
ORACLE_PORT=29004

PG_ORCH_CONTAINER="gims_orchestrator_dmz"
PG_ORCH_PORT=29001

PG_PROVIDE_CONTAINER="gims_api_provider_pg"
PG_PROVIDE_PORT=29006

echo "=========================================="
echo " 전처리 Agent 개발 환경 셋업"
echo "=========================================="
echo ""

# ----- 1. Docker 확인 -----
command -v docker >/dev/null 2>&1 || err "Docker가 설치되어 있지 않습니다."
log "Docker 확인 완료"

# ----- 2. Oracle 컨테이너 (29004) -----
start_container() {
    local name=$1 port=$2 image=$3
    shift 3
    if docker ps --format '{{.Names}}' | grep -q "^${name}$"; then
        log "${name} 이미 실행 중 (:${port})"
    elif docker ps -a --format '{{.Names}}' | grep -q "^${name}$"; then
        warn "${name} 시작 중..."
        docker start ${name}
    else
        warn "${name} 생성 중..."
        docker run -d --name ${name} -p ${port}:${3:-5432} "$@" ${image}
    fi
}

# Oracle
if docker ps --format '{{.Names}}' | grep -q "^${ORACLE_CONTAINER}$"; then
    log "${ORACLE_CONTAINER} 이미 실행 중 (:${ORACLE_PORT})"
elif docker ps -a --format '{{.Names}}' | grep -q "^${ORACLE_CONTAINER}$"; then
    warn "${ORACLE_CONTAINER} 시작 중..."
    docker start ${ORACLE_CONTAINER}
else
    warn "${ORACLE_CONTAINER} 생성 중 (최초 1회, 1~2분 소요)..."
    docker run -d \
        --name ${ORACLE_CONTAINER} \
        -p ${ORACLE_PORT}:1521 \
        -e ORACLE_PASSWORD=1111 \
        -e APP_USER=k1m \
        -e APP_USER_PASSWORD=1111 \
        gvenzl/oracle-xe:21-slim
fi

# Oracle 준비 대기
warn "Oracle 준비 대기 중..."
for i in $(seq 1 60); do
    if docker exec ${ORACLE_CONTAINER} sqlplus -s k1m/1111@//localhost:1521/XEPDB1 <<< "SELECT 1 FROM DUAL;" >/dev/null 2>&1; then
        log "Oracle 준비 완료"
        break
    fi
    if [ $i -eq 60 ]; then
        err "Oracle 기동 타임아웃 (60초). 'docker logs ${ORACLE_CONTAINER}' 확인"
    fi
    sleep 2
done

# ----- 3. PostgreSQL — Orchestrator (29001) -----
if docker ps --format '{{.Names}}' | grep -q "^${PG_ORCH_CONTAINER}$"; then
    log "${PG_ORCH_CONTAINER} 이미 실행 중 (:${PG_ORCH_PORT})"
elif docker ps -a --format '{{.Names}}' | grep -q "^${PG_ORCH_CONTAINER}$"; then
    warn "${PG_ORCH_CONTAINER} 시작 중..."
    docker start ${PG_ORCH_CONTAINER}
else
    warn "${PG_ORCH_CONTAINER} 생성 중..."
    docker run -d \
        --name ${PG_ORCH_CONTAINER} \
        -p ${PG_ORCH_PORT}:5432 \
        -e POSTGRES_USER=k1m \
        -e POSTGRES_PASSWORD=1111 \
        postgres:16
fi

# ----- 4. PostgreSQL — API Provider (29006, 신규) -----
if docker ps --format '{{.Names}}' | grep -q "^${PG_PROVIDE_CONTAINER}$"; then
    log "${PG_PROVIDE_CONTAINER} 이미 실행 중 (:${PG_PROVIDE_PORT})"
elif docker ps -a --format '{{.Names}}' | grep -q "^${PG_PROVIDE_CONTAINER}$"; then
    warn "${PG_PROVIDE_CONTAINER} 시작 중..."
    docker start ${PG_PROVIDE_CONTAINER}
else
    warn "${PG_PROVIDE_CONTAINER} 생성 중..."
    docker run -d \
        --name ${PG_PROVIDE_CONTAINER} \
        -p ${PG_PROVIDE_PORT}:5432 \
        -e POSTGRES_USER=k1m \
        -e POSTGRES_PASSWORD=1111 \
        postgres:16
fi

# PG 준비 대기
sleep 3
for i in $(seq 1 20); do
    if docker exec ${PG_ORCH_CONTAINER} pg_isready -U k1m >/dev/null 2>&1 \
       && docker exec ${PG_PROVIDE_CONTAINER} pg_isready -U k1m >/dev/null 2>&1; then
        log "PostgreSQL 준비 완료 (orchestrator:${PG_ORCH_PORT}, provider:${PG_PROVIDE_PORT})"
        break
    fi
    sleep 1
done

# ----- 5. PG 데이터베이스 생성 -----
warn "PostgreSQL 데이터베이스 확인 중..."

# Orchestrator DB (29001)
docker exec ${PG_ORCH_CONTAINER} psql -U k1m -d postgres -tc \
    "SELECT 1 FROM pg_database WHERE datname='orchestrator'" | grep -q 1 \
    || docker exec ${PG_ORCH_CONTAINER} psql -U k1m -d postgres -c "CREATE DATABASE orchestrator;"
log "orchestrator DB (${PG_ORCH_PORT})"

# api_provider DB는 별도 PG (29006)에 기본 DB(k1m) 사용
log "api_provider DB (${PG_PROVIDE_PORT}, 기본 DB: k1m)"

# ----- 6. Oracle — 자체 관리 테이블 (sync_log, execution) -----
warn "Oracle 관리 테이블 생성 중..."

docker exec -i ${ORACLE_CONTAINER} sqlplus -s k1m/1111@//localhost:1521/XEPDB1 <<'EOSQL'
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'SYNC_LOG';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE SYNC_LOG (
            ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
            EXECUTION_ID VARCHAR2(100) NOT NULL,
            STEP_ID VARCHAR2(50),
            MAPPING_NAME VARCHAR2(100),
            SOURCE_TABLES VARCHAR2(4000),
            TARGET_TABLES VARCHAR2(4000),
            READ_COUNT NUMBER,
            WRITE_COUNT NUMBER,
            FAILED_COUNT NUMBER,
            SKIP_COUNT NUMBER,
            FAILED_KEYS VARCHAR2(4000),
            ERROR_SUMMARY VARCHAR2(4000),
            SOURCE_PK_COLUMN VARCHAR2(100),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
            CONSTRAINT PK_SYNC_LOG PRIMARY KEY (ID)
        )';
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SYNC_LOG_EXEC ON SYNC_LOG (EXECUTION_ID)';
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_SYNC_LOG_MAP ON SYNC_LOG (EXECUTION_ID, MAPPING_NAME)';
    END IF;

    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'EXECUTION';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE EXECUTION (
            ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
            EXECUTION_ID VARCHAR2(100) NOT NULL,
            AGENT_ID VARCHAR2(100),
            SOURCE_DATASOURCE_ID VARCHAR2(50),
            TARGET_DATASOURCE_ID VARCHAR2(50),
            PARENT_EXECUTION_ID VARCHAR2(100),
            STATUS VARCHAR2(20),
            STARTED_AT TIMESTAMP,
            FINISHED_AT TIMESTAMP,
            DURATION_MS NUMBER,
            TOTAL_READ_COUNT NUMBER,
            TOTAL_WRITE_COUNT NUMBER,
            TOTAL_SKIP_COUNT NUMBER,
            ERROR_MESSAGE VARCHAR2(4000),
            CONSTRAINT PK_EXECUTION PRIMARY KEY (ID),
            CONSTRAINT UK_EXECUTION_EID UNIQUE (EXECUTION_ID)
        )';
    END IF;
END;
/
EOSQL
log "Oracle 관리 테이블 (SYNC_LOG, EXECUTION)"

# ----- 7. Oracle — GIMS 원본 테이블 (전처리 소스) -----
warn "Oracle 원본 테이블 생성 중..."

docker exec -i ${ORACLE_CONTAINER} sqlplus -s k1m/1111@//localhost:1521/XEPDB1 <<'EOSQL'
DECLARE
    v_cnt NUMBER;
    PROCEDURE create_if_not_exists(p_ddl VARCHAR2, p_table VARCHAR2) IS
    BEGIN
        SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = p_table;
        IF v_cnt = 0 THEN
            EXECUTE IMMEDIATE p_ddl;
        END IF;
    END;
BEGIN

    create_if_not_exists('
    CREATE TABLE TM_GD10001 (
        GENNUM NUMBER NOT NULL, SPOT_NM VARCHAR2(100), JOSACODE VARCHAR2(20),
        BRTC_NM VARCHAR2(40), SIGUN_NM VARCHAR2(30), EMD_NM VARCHAR2(30),
        LI_NM VARCHAR2(40), ADDR VARCHAR2(250),
        LA_VALUE NUMBER, LO_VALUE NUMBER, AL_VALUE NUMBER,
        WELL_STLE_CODE VARCHAR2(10), LEGALDONG_CODE VARCHAR2(20),
        LINK_STATUS VARCHAR2(20) DEFAULT ''PENDING'', EXECUTION_ID VARCHAR2(100),
        SOURCE_REFS VARCHAR2(4000), EXTRACTED_AT TIMESTAMP, UPDATED_AT TIMESTAMP
    )', 'TM_GD10001');

    create_if_not_exists('
    CREATE TABLE TM_GD30301 (
        QLTWTR_INSPCT_SN NUMBER NOT NULL, GENNUM NUMBER NOT NULL,
        INVSTG_YEAR VARCHAR2(4), ODR NUMBER, DPH_CL_CODE CHAR(1), DPH_VALUE NUMBER,
        WATSMP_DE VARCHAR2(8), QLTWTR_INSPCT_DE VARCHAR2(8),
        DTA_INPUT_DE VARCHAR2(8), DCSN_DE VARCHAR2(8),
        FRST_REGIST_DT DATE, LAST_CHANGE_DT DATE,
        UGRWTR_PRPOS_CODE CHAR(2), DRNK_AT CHAR(1),
        UGRWTR_WQN_INPUT_INSTT_CODE VARCHAR2(5),
        QLTWTR_INSPCT_IMPRTY_RESN_CTNT VARCHAR2(4000),
        BRTC_NM VARCHAR2(40), SIGUN_NM VARCHAR2(30), EMD_NM VARCHAR2(30),
        LI_NM VARCHAR2(40), ADDR VARCHAR2(250), PUBWELL_AT CHAR(1),
        LINK_STATUS VARCHAR2(20) DEFAULT ''PENDING'', EXECUTION_ID VARCHAR2(100),
        SOURCE_REFS VARCHAR2(4000), EXTRACTED_AT TIMESTAMP, UPDATED_AT TIMESTAMP
    )', 'TM_GD30301');

    create_if_not_exists('
    CREATE TABLE TM_GD30302 (
        QLTWTR_INSPCT_SN NUMBER NOT NULL, WLTTS_ID_CODE CHAR(4) NOT NULL,
        RESULT_VALUE VARCHAR2(20),
        LINK_STATUS VARCHAR2(20) DEFAULT ''PENDING'', EXECUTION_ID VARCHAR2(100),
        SOURCE_REFS VARCHAR2(4000), EXTRACTED_AT TIMESTAMP, UPDATED_AT TIMESTAMP
    )', 'TM_GD30302');

    create_if_not_exists('
    CREATE TABLE TM_GD30310 (
        DTA_STDR_YEAR VARCHAR2(4), WLTTS_ID_CODE CHAR(4),
        WLTTS_NM VARCHAR2(100), UNIT_NM VARCHAR2(20),
        LINK_STATUS VARCHAR2(20) DEFAULT ''PENDING'', EXECUTION_ID VARCHAR2(100),
        SOURCE_REFS VARCHAR2(4000), EXTRACTED_AT TIMESTAMP, UPDATED_AT TIMESTAMP
    )', 'TM_GD30310');

    create_if_not_exists('
    CREATE TABLE TM_GD00203 (
        BRTC_NM VARCHAR2(40), SIGUN_NM VARCHAR2(40), EMD_NM VARCHAR2(30), LI_NM VARCHAR2(40),
        POPLTN_VALUE NUMBER, LPCD_CTNT VARCHAR2(100),
        DMAND_QUA_VALUE NUMBER, SUPLY_PSBLQY_VALUE NUMBER, NSTT_VALUE NUMBER,
        TOT_PUBWELL_CO NUMBER, USE_PUBWELL_CO NUMBER,
        LINK_STATUS VARCHAR2(20) DEFAULT ''PENDING'', EXECUTION_ID VARCHAR2(100),
        SOURCE_REFS VARCHAR2(4000), EXTRACTED_AT TIMESTAMP, UPDATED_AT TIMESTAMP
    )', 'TM_GD00203');

    create_if_not_exists('
    CREATE TABLE TM_GD50001 (
        GENNUM NUMBER, INSPCT_YEAR VARCHAR2(4), INSPCT_NM VARCHAR2(200),
        LINK_STATUS VARCHAR2(20) DEFAULT ''PENDING'', EXECUTION_ID VARCHAR2(100),
        SOURCE_REFS VARCHAR2(4000), EXTRACTED_AT TIMESTAMP, UPDATED_AT TIMESTAMP
    )', 'TM_GD50001');

    create_if_not_exists('
    CREATE TABLE TM_GD60001 (
        SPOT_ID VARCHAR2(20) NOT NULL, OBSRVT_ID VARCHAR2(30), OBSRVT_NM VARCHAR2(100),
        SPOT_TY_MNG_WORD_NM VARCHAR2(100), INSTL_DE VARCHAR2(8),
        REMARK_CTNT VARCHAR2(4000), FRST_REGIST_DT DATE,
        LINK_STATUS VARCHAR2(20) DEFAULT ''PENDING'', EXECUTION_ID VARCHAR2(100),
        SOURCE_REFS VARCHAR2(4000), EXTRACTED_AT TIMESTAMP, UPDATED_AT TIMESTAMP
    )', 'TM_GD60001');

    create_if_not_exists('
    CREATE TABLE TM_GD60002 (
        SPOT_ID VARCHAR2(20) NOT NULL, RDNM_ADDR VARCHAR2(250), MNG_INSTT_NM VARCHAR2(100),
        LINK_STATUS VARCHAR2(20) DEFAULT ''PENDING'', EXECUTION_ID VARCHAR2(100),
        SOURCE_REFS VARCHAR2(4000), EXTRACTED_AT TIMESTAMP, UPDATED_AT TIMESTAMP
    )', 'TM_GD60002');

    create_if_not_exists('
    CREATE TABLE TM_GD60101 (
        RESULT_ID NUMBER NOT NULL, TAG_CTNT VARCHAR2(50), OBSR_IEM_ID NUMBER,
        SPOT_ID VARCHAR2(20), TIME_UNIT_ID NUMBER,
        LINK_STATUS VARCHAR2(20) DEFAULT ''PENDING'', EXECUTION_ID VARCHAR2(100),
        SOURCE_REFS VARCHAR2(4000), EXTRACTED_AT TIMESTAMP, UPDATED_AT TIMESTAMP
    )', 'TM_GD60101');

    create_if_not_exists('
    CREATE TABLE TM_GD60130 (
        GENNUM NUMBER, SPOT_ID VARCHAR2(20), INSTL_DPH_VALUE NUMBER,
        SUPRR_DGG_CALBR VARCHAR2(20), OBSR_IEM_NM VARCHAR2(100),
        OBSR_CYCLE_CTNT VARCHAR2(100), UGRWTR_DTL_PRPOS_CODE VARCHAR2(10),
        DRNK_AT CHAR(1), PRMISN_DCLR_NO VARCHAR2(50), CSNG_HG NUMBER,
        LINK_STATUS VARCHAR2(20) DEFAULT ''PENDING'', EXECUTION_ID VARCHAR2(100),
        SOURCE_REFS VARCHAR2(4000), EXTRACTED_AT TIMESTAMP, UPDATED_AT TIMESTAMP
    )', 'TM_GD60130');

    create_if_not_exists('
    CREATE TABLE TM_GD70002 (
        SPOT_ID VARCHAR2(20), CNTC_TRGET_IP VARCHAR2(50), CNTC_TRGET_PORT_CTNT VARCHAR2(10),
        LINK_STATUS VARCHAR2(20) DEFAULT ''PENDING'', EXECUTION_ID VARCHAR2(100),
        SOURCE_REFS VARCHAR2(4000), EXTRACTED_AT TIMESTAMP, UPDATED_AT TIMESTAMP
    )', 'TM_GD70002');

    create_if_not_exists('
    CREATE TABLE PM_GD60201 (
        RESULT_ID NUMBER NOT NULL, OBSR_DT DATE, OBSR_DTA_VALUE NUMBER, QLITY_ID NUMBER,
        LINK_STATUS VARCHAR2(20) DEFAULT ''PENDING'', EXECUTION_ID VARCHAR2(100),
        SOURCE_REFS VARCHAR2(4000), EXTRACTED_AT TIMESTAMP, UPDATED_AT TIMESTAMP
    )', 'PM_GD60201');

    create_if_not_exists('
    CREATE TABLE TC_GD00002 (
        CODE_ID VARCHAR2(20), CODE_NM VARCHAR2(100), CODE_GROUP_ID VARCHAR2(20), SORT_ORDER NUMBER,
        LINK_STATUS VARCHAR2(20) DEFAULT ''PENDING'', EXECUTION_ID VARCHAR2(100),
        SOURCE_REFS VARCHAR2(4000), EXTRACTED_AT TIMESTAMP, UPDATED_AT TIMESTAMP
    )', 'TC_GD00002');

    create_if_not_exists('
    CREATE TABLE TC_GD00100 (
        ADMINIST_ZONE_CODE VARCHAR2(10), ADMINIST_ZONE_NM VARCHAR2(100),
        LINK_STATUS VARCHAR2(20) DEFAULT ''PENDING'', EXECUTION_ID VARCHAR2(100),
        SOURCE_REFS VARCHAR2(4000), EXTRACTED_AT TIMESTAMP, UPDATED_AT TIMESTAMP
    )', 'TC_GD00100');

    create_if_not_exists('
    CREATE TABLE WT_DREAM_PERMWELL_PUBLIC (
        OBJECTID NUMBER, PERM_NT_NO VARCHAR2(50), BRTC_NM VARCHAR2(40), SIGUN_NM VARCHAR2(40),
        DPH NUMBER, DIG_DIAM NUMBER,
        LINK_STATUS VARCHAR2(20) DEFAULT ''PENDING'', EXECUTION_ID VARCHAR2(100),
        SOURCE_REFS VARCHAR2(4000), EXTRACTED_AT TIMESTAMP, UPDATED_AT TIMESTAMP
    )', 'WT_DREAM_PERMWELL_PUBLIC');

END;
/
COMMIT;
EOSQL
log "Oracle 원본 테이블 15개 생성 완료"

# ----- 8. Oracle — 테스트 샘플 데이터 -----
warn "테스트 샘플 데이터 삽입 중..."

docker exec -i ${ORACLE_CONTAINER} sqlplus -s k1m/1111@//localhost:1521/XEPDB1 <<'EOSQL'
MERGE INTO TM_GD30302 T USING (SELECT 1001 AS SN, '0001' AS CODE FROM DUAL) S
ON (T.QLTWTR_INSPCT_SN = S.SN AND T.WLTTS_ID_CODE = S.CODE)
WHEN NOT MATCHED THEN INSERT (QLTWTR_INSPCT_SN, WLTTS_ID_CODE, RESULT_VALUE) VALUES (1001, '0001', '1.5');

MERGE INTO TM_GD30302 T USING (SELECT 1001 AS SN, '0002' AS CODE FROM DUAL) S
ON (T.QLTWTR_INSPCT_SN = S.SN AND T.WLTTS_ID_CODE = S.CODE)
WHEN NOT MATCHED THEN INSERT (QLTWTR_INSPCT_SN, WLTTS_ID_CODE, RESULT_VALUE) VALUES (1001, '0002', '0.3');

MERGE INTO TM_GD30302 T USING (SELECT 1001 AS SN, '0003' AS CODE FROM DUAL) S
ON (T.QLTWTR_INSPCT_SN = S.SN AND T.WLTTS_ID_CODE = S.CODE)
WHEN NOT MATCHED THEN INSERT (QLTWTR_INSPCT_SN, WLTTS_ID_CODE, RESULT_VALUE) VALUES (1001, '0003', '2.1');

MERGE INTO TM_GD30302 T USING (SELECT 1002 AS SN, '0001' AS CODE FROM DUAL) S
ON (T.QLTWTR_INSPCT_SN = S.SN AND T.WLTTS_ID_CODE = S.CODE)
WHEN NOT MATCHED THEN INSERT (QLTWTR_INSPCT_SN, WLTTS_ID_CODE, RESULT_VALUE) VALUES (1002, '0001', '3.0');

MERGE INTO TM_GD30301 T USING (SELECT 1001 AS SN FROM DUAL) S
ON (T.QLTWTR_INSPCT_SN = S.SN)
WHEN NOT MATCHED THEN INSERT (QLTWTR_INSPCT_SN, GENNUM, INVSTG_YEAR, BRTC_NM, SIGUN_NM)
VALUES (1001, 300001, '2025', '대전광역시', '유성구');

MERGE INTO TM_GD30301 T USING (SELECT 1002 AS SN FROM DUAL) S
ON (T.QLTWTR_INSPCT_SN = S.SN)
WHEN NOT MATCHED THEN INSERT (QLTWTR_INSPCT_SN, GENNUM, INVSTG_YEAR, BRTC_NM, SIGUN_NM)
VALUES (1002, 300002, '2025', '서울특별시', '강남구');

MERGE INTO TM_GD10001 T USING (SELECT 300001 AS G FROM DUAL) S
ON (T.GENNUM = S.G)
WHEN NOT MATCHED THEN INSERT (GENNUM, SPOT_NM, JOSACODE, BRTC_NM, SIGUN_NM, LA_VALUE, LO_VALUE, AL_VALUE)
VALUES (300001, '테스트관정1', '105', '대전광역시', '유성구', 36.362, 127.356, 75.3);

MERGE INTO TM_GD10001 T USING (SELECT 300002 AS G FROM DUAL) S
ON (T.GENNUM = S.G)
WHEN NOT MATCHED THEN INSERT (GENNUM, SPOT_NM, JOSACODE, BRTC_NM, SIGUN_NM, LA_VALUE, LO_VALUE, AL_VALUE)
VALUES (300002, '테스트관정2', '101', '서울특별시', '강남구', 37.497, 127.027, 25.1);

MERGE INTO TM_GD00203 T USING (SELECT '대전광역시' AS B, '유성구' AS S FROM DUAL) SRC
ON (T.BRTC_NM = SRC.B AND T.SIGUN_NM = SRC.S)
WHEN NOT MATCHED THEN INSERT (BRTC_NM, SIGUN_NM, POPLTN_VALUE, TOT_PUBWELL_CO, USE_PUBWELL_CO)
VALUES ('대전광역시', '유성구', 350000, 120, 95);

-- TM_GD60001 (관측점)
MERGE INTO TM_GD60001 T USING (SELECT 'SP001' AS S FROM DUAL) SRC ON (T.SPOT_ID = SRC.S)
WHEN NOT MATCHED THEN INSERT (SPOT_ID, OBSRVT_ID, OBSRVT_NM, SPOT_TY_MNG_WORD_NM)
VALUES ('SP001', 'OBS-001', '테스트보조관측소1', '보조지하수관측망');

MERGE INTO TM_GD60001 T USING (SELECT 'SP002' AS S FROM DUAL) SRC ON (T.SPOT_ID = SRC.S)
WHEN NOT MATCHED THEN INSERT (SPOT_ID, OBSRVT_ID, OBSRVT_NM, SPOT_TY_MNG_WORD_NM)
VALUES ('SP002', 'OBS-002', '테스트보조관측소2', '수동보조지하수관측망');

-- TM_GD60002 (관측점 상세)
MERGE INTO TM_GD60002 T USING (SELECT 'SP001' AS S FROM DUAL) SRC ON (T.SPOT_ID = SRC.S)
WHEN NOT MATCHED THEN INSERT (SPOT_ID, RDNM_ADDR, MNG_INSTT_NM)
VALUES ('SP001', '대전광역시 유성구 테스트로 1', '한국지질자원연구원');

-- TM_GD60101 (관측 지점/항목)
MERGE INTO TM_GD60101 T USING (SELECT 5001 AS R FROM DUAL) SRC ON (T.RESULT_ID = SRC.R)
WHEN NOT MATCHED THEN INSERT (RESULT_ID, TAG_CTNT, OBSR_IEM_ID, SPOT_ID, TIME_UNIT_ID)
VALUES (5001, '300001', 5, 'SP001', 4);

MERGE INTO TM_GD60101 T USING (SELECT 5002 AS R FROM DUAL) SRC ON (T.RESULT_ID = SRC.R)
WHEN NOT MATCHED THEN INSERT (RESULT_ID, TAG_CTNT, OBSR_IEM_ID, SPOT_ID, TIME_UNIT_ID)
VALUES (5002, '300001', 163, 'SP001', 4);

MERGE INTO TM_GD60101 T USING (SELECT 5003 AS R FROM DUAL) SRC ON (T.RESULT_ID = SRC.R)
WHEN NOT MATCHED THEN INSERT (RESULT_ID, TAG_CTNT, OBSR_IEM_ID, SPOT_ID, TIME_UNIT_ID)
VALUES (5003, '300001', 52, 'SP001', 4);

-- TM_GD60130 (관측 지점 상세)
MERGE INTO TM_GD60130 T USING (SELECT 300001 AS G, 'SP001' AS S FROM DUAL) SRC
ON (T.GENNUM = SRC.G AND T.SPOT_ID = SRC.S)
WHEN NOT MATCHED THEN INSERT (GENNUM, SPOT_ID, INSTL_DPH_VALUE, OBSR_IEM_NM, DRNK_AT)
VALUES (300001, 'SP001', 50.5, '수위', 'Y');

-- TM_GD70002 (DB 접속정보)
MERGE INTO TM_GD70002 T USING (SELECT 'SP001' AS S FROM DUAL) SRC ON (T.SPOT_ID = SRC.S)
WHEN NOT MATCHED THEN INSERT (SPOT_ID, CNTC_TRGET_IP, CNTC_TRGET_PORT_CTNT)
VALUES ('SP001', '192.168.1.100', '1521');

-- PM_GD60201 (관측 데이터)
MERGE INTO PM_GD60201 T USING (SELECT 5001 AS R, TO_DATE('20250401','YYYYMMDD') AS D FROM DUAL) SRC
ON (T.RESULT_ID = SRC.R AND T.OBSR_DT = SRC.D)
WHEN NOT MATCHED THEN INSERT (RESULT_ID, OBSR_DT, OBSR_DTA_VALUE, QLITY_ID)
VALUES (5001, TO_DATE('20250401','YYYYMMDD'), 12.35, 1);

MERGE INTO PM_GD60201 T USING (SELECT 5002 AS R, TO_DATE('20250401','YYYYMMDD') AS D FROM DUAL) SRC
ON (T.RESULT_ID = SRC.R AND T.OBSR_DT = SRC.D)
WHEN NOT MATCHED THEN INSERT (RESULT_ID, OBSR_DT, OBSR_DTA_VALUE, QLITY_ID)
VALUES (5002, TO_DATE('20250401','YYYYMMDD'), 15.2, 1);

MERGE INTO PM_GD60201 T USING (SELECT 5003 AS R, TO_DATE('20250401','YYYYMMDD') AS D FROM DUAL) SRC
ON (T.RESULT_ID = SRC.R AND T.OBSR_DT = SRC.D)
WHEN NOT MATCHED THEN INSERT (RESULT_ID, OBSR_DT, OBSR_DTA_VALUE, QLITY_ID)
VALUES (5003, TO_DATE('20250401','YYYYMMDD'), 320, 1);

-- TM_GD50001 (영향조사)
MERGE INTO TM_GD50001 T USING (SELECT 300001 AS G, '2025' AS Y FROM DUAL) SRC
ON (T.GENNUM = SRC.G AND T.INSPCT_YEAR = SRC.Y)
WHEN NOT MATCHED THEN INSERT (GENNUM, INSPCT_YEAR, INSPCT_NM)
VALUES (300001, '2025', '테스트 영향조사');

-- TM_GD30310 (수질검사 항목)
MERGE INTO TM_GD30310 T USING (SELECT '2025' AS Y, '0001' AS C FROM DUAL) SRC
ON (T.DTA_STDR_YEAR = SRC.Y AND T.WLTTS_ID_CODE = SRC.C)
WHEN NOT MATCHED THEN INSERT (DTA_STDR_YEAR, WLTTS_ID_CODE, WLTTS_NM, UNIT_NM)
VALUES ('2025', '0001', '일반세균', 'CFU/mL');

MERGE INTO TM_GD30310 T USING (SELECT '2025' AS Y, '0002' AS C FROM DUAL) SRC
ON (T.DTA_STDR_YEAR = SRC.Y AND T.WLTTS_ID_CODE = SRC.C)
WHEN NOT MATCHED THEN INSERT (DTA_STDR_YEAR, WLTTS_ID_CODE, WLTTS_NM, UNIT_NM)
VALUES ('2025', '0002', '총대장균군', 'MPN/100mL');

-- TC_GD00002 (공통코드)
MERGE INTO TC_GD00002 T USING (SELECT '105' AS C FROM DUAL) SRC ON (T.CODE_ID = SRC.C)
WHEN NOT MATCHED THEN INSERT (CODE_ID, CODE_NM, CODE_GROUP_ID, SORT_ORDER)
VALUES ('105', '보조관측망', 'JOSACODE', 1);

-- TC_GD00100 (행정구역)
MERGE INTO TC_GD00100 T USING (SELECT '3020000000' AS C FROM DUAL) SRC ON (T.ADMINIST_ZONE_CODE = SRC.C)
WHEN NOT MATCHED THEN INSERT (ADMINIST_ZONE_CODE, ADMINIST_ZONE_NM)
VALUES ('3020000000', '대전광역시 유성구');

-- WT_DREAM_PERMWELL_PUBLIC (공공관정)
MERGE INTO WT_DREAM_PERMWELL_PUBLIC T USING (SELECT 1 AS O FROM DUAL) SRC ON (T.OBJECTID = SRC.O)
WHEN NOT MATCHED THEN INSERT (OBJECTID, PERM_NT_NO, BRTC_NM, SIGUN_NM, DPH, DIG_DIAM)
VALUES (1, 'TEST-PERM-001', '대전광역시', '유성구', 100, 200);

MERGE INTO WT_DREAM_PERMWELL_PUBLIC T USING (SELECT 2 AS O FROM DUAL) SRC ON (T.OBJECTID = SRC.O)
WHEN NOT MATCHED THEN INSERT (OBJECTID, PERM_NT_NO, BRTC_NM, SIGUN_NM, DPH, DIG_DIAM)
VALUES (2, 'TEST-PERM-002', '서울특별시', '강남구', 80, 150);

COMMIT;
EOSQL
log "테스트 샘플 데이터 삽입 완료 (전 테이블)"

# ----- 9. PG(29006) — TM_PROVIDE_* 테스트용 테이블 -----
warn "PG API Provider 테이블 생성 중..."

docker exec -i ${PG_PROVIDE_CONTAINER} psql -U k1m <<'EOSQL'

-- Type A: 단순 복사 대상
CREATE TABLE IF NOT EXISTS tm_provide_drought119 (
    objectid INTEGER, perm_nt_no VARCHAR(50), brtc_nm VARCHAR(40), sigun_nm VARCHAR(40),
    dph NUMERIC, dig_diam NUMERIC,
    execution_id VARCHAR(100), source_refs VARCHAR(4000), updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tm_provide_ngw03 (
    qltwtr_inspct_sn NUMERIC NOT NULL, gennum NUMERIC, invstg_year VARCHAR(4),
    odr NUMERIC, dph_cl_code CHAR(1), dph_value NUMERIC,
    watsmp_de VARCHAR(8), qltwtr_inspct_de VARCHAR(8),
    brtc_nm VARCHAR(40), sigun_nm VARCHAR(30), emd_nm VARCHAR(30),
    addr VARCHAR(250), pubwell_at CHAR(1),
    execution_id VARCHAR(100), source_refs VARCHAR(4000), updated_at TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (qltwtr_inspct_sn)
);

CREATE TABLE IF NOT EXISTS tm_provide_ngw08 (
    brtc_nm VARCHAR(40), sigun_nm VARCHAR(40), emd_nm VARCHAR(30), li_nm VARCHAR(40),
    popltn_value NUMERIC, tot_pubwell_co NUMERIC, use_pubwell_co NUMERIC,
    execution_id VARCHAR(100), source_refs VARCHAR(4000), updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tm_provide_ngw09 (
    objectid INTEGER, perm_nt_no VARCHAR(50), brtc_nm VARCHAR(40), sigun_nm VARCHAR(40),
    dph NUMERIC, dig_diam NUMERIC,
    execution_id VARCHAR(100), source_refs VARCHAR(4000), updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tm_provide_permwell (
    sn SERIAL PRIMARY KEY,
    source_refs VARCHAR(4000),
    execution_id VARCHAR(100), updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tm_provide_general (
    gennum NUMERIC NOT NULL, spot_nm VARCHAR(100), josacode VARCHAR(20),
    brtc_nm VARCHAR(40), sigun_nm VARCHAR(30),
    la_value NUMERIC, lo_value NUMERIC, al_value NUMERIC,
    execution_id VARCHAR(100), source_refs VARCHAR(4000), updated_at TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (gennum)
);

CREATE TABLE IF NOT EXISTS tm_provide_gtest (
    id SERIAL PRIMARY KEY,
    execution_id VARCHAR(100), source_refs VARCHAR(4000), updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tm_provide_yhjs (
    gennum NUMERIC, inspct_year VARCHAR(4), inspct_nm VARCHAR(200),
    execution_id VARCHAR(100), source_refs VARCHAR(4000), updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tm_provide_inspection (
    dta_stdr_year VARCHAR(4), wltts_id_code CHAR(4),
    wltts_nm VARCHAR(100), unit_nm VARCHAR(20),
    execution_id VARCHAR(100), source_refs VARCHAR(4000), updated_at TIMESTAMP DEFAULT NOW()
);

-- Type B: 전처리 대상
CREATE TABLE IF NOT EXISTS tm_provide_ngw04 (
    qltwtr_inspct_sn NUMERIC NOT NULL,
    wt_tot_col_cnts VARCHAR(100), wt_tot_clf VARCHAR(100),
    wt_fcl_cfs VARCHAR(100), wt_esc_col VARCHAR(100), wt_plb VARCHAR(100),
    execution_id VARCHAR(100), source_refs VARCHAR(4000), updated_at TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (qltwtr_inspct_sn)
);

CREATE TABLE IF NOT EXISTS tm_provide_water_quality (
    gennum NUMERIC NOT NULL, qltwtr_inspct_sn NUMERIC NOT NULL,
    spot_nm VARCHAR(100), brtc_nm VARCHAR(40), sigun_nm VARCHAR(30),
    execution_id VARCHAR(100), source_refs VARCHAR(4000), updated_at TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (gennum, qltwtr_inspct_sn)
);

CREATE TABLE IF NOT EXISTS tm_provide_general_105 (
    gennum NUMERIC NOT NULL,
    obsrvt_nm VARCHAR(100), brtc_nm VARCHAR(40), sigun_nm VARCHAR(30),
    la_value NUMERIC, lo_value NUMERIC,
    instl_dph_value NUMERIC, rdnm_addr VARCHAR(250), obsr_iem_nm VARCHAR(100),
    execution_id VARCHAR(100), source_refs VARCHAR(4000), updated_at TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (gennum)
);

CREATE TABLE IF NOT EXISTS tm_provide_observation (
    wlobscd VARCHAR(20) NOT NULL,
    obsnm VARCHAR(100), addr VARCHAR(250),
    wl NUMERIC, flw NUMERIC,
    execution_id VARCHAR(100), source_refs VARCHAR(4000), updated_at TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (wlobscd)
);

CREATE TABLE IF NOT EXISTS tm_provide_rainfall (
    rfobscd VARCHAR(20) NOT NULL,
    obsnm VARCHAR(100), addr VARCHAR(250),
    rf NUMERIC, acurf NUMERIC,
    execution_id VARCHAR(100), source_refs VARCHAR(4000), updated_at TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (rfobscd)
);

CREATE TABLE IF NOT EXISTS tm_provide_linkage_chart (
    gennum NUMERIC NOT NULL, ymd VARCHAR(8) NOT NULL,
    elev NUMERIC, wtemp NUMERIC, lev NUMERIC, ec NUMERIC,
    execution_id VARCHAR(100), source_refs VARCHAR(4000), updated_at TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (gennum, ymd)
);

EOSQL
log "PG TM_PROVIDE_* 테이블 15개 생성 완료 (Type A: 9, Type B: 6)"

# ----- 10. JASYPT 환경 변수 -----
if [ -z "$JASYPT_PASSWORD" ]; then
    export JASYPT_PASSWORD=sync-pipeline-secret-key-2024
    log "JASYPT_PASSWORD 설정 완료 (현재 세션)"
    warn "영구 설정: 아래 명령어를 실행하세요"
    echo "  Linux/Mac: echo 'export JASYPT_PASSWORD=sync-pipeline-secret-key-2024' >> ~/.bashrc"
    echo "  Windows:   setx JASYPT_PASSWORD \"sync-pipeline-secret-key-2024\""
else
    log "JASYPT_PASSWORD 이미 설정됨"
fi

# ----- 10. 프로젝트 빌드 -----
warn "sync-agent-common 빌드 중..."
cd "${PROJECT_DIR}/sync-agent-common"
./gradlew clean build -x test --quiet || err "common 빌드 실패"
log "sync-agent-common 빌드 완료"

warn "JAR 복사 중..."
cp build/libs/sync-agent-common-*.jar "${PROJECT_DIR}/sync-agent-bojo-int/libs/"
log "JAR → sync-agent-bojo-int/libs/ 복사 완료"

warn "sync-agent-bojo-int 빌드 중..."
cd "${PROJECT_DIR}/sync-agent-bojo-int"
./gradlew clean build -x test --quiet || err "bojo-int 빌드 실패"
log "sync-agent-bojo-int 빌드 완료"

# ----- 11. 결과 요약 -----
cd "${PROJECT_DIR}"
echo ""
echo "=========================================="
echo " 셋업 완료!"
echo "=========================================="
echo ""
echo " DB 환경:"
echo "   Oracle (소스):     localhost:${ORACLE_PORT}/XEPDB1       (k1m/1111)"
echo "   PG Orchestrator:   localhost:${PG_ORCH_PORT}/orchestrator (k1m/1111)"
echo "   PG API Provider:   localhost:${PG_PROVIDE_PORT}            (k1m/1111)"
echo ""
echo " 빌드 완료: sync-agent-common → sync-agent-bojo-int"
echo ""
echo " Agent 기동:"
echo "   cd sync-agent-bojo-int && ./gradlew bootRun"
echo ""
echo " 테스트 실행:"
echo "   curl -X POST http://localhost:8092/api/pipeline/execute \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"agentCode\":\"internal-provide-preprocessor\"}'"
echo ""
