-- RGETNKCNO01 (케이싱) — DDL에 PK 제약 없음, 레거시 WHERE 키 기준으로 유니크 확인
-- 결과 0건이면 REL_TRANS_CGG_CODE, PERM_NT_NO, DIG_ORD를 PK로 사용 가능
SELECT REL_TRANS_CGG_CODE, PERM_NT_NO, DIG_ORD, COUNT(*) cnt
FROM RGETNKCNO01
GROUP BY REL_TRANS_CGG_CODE, PERM_NT_NO, DIG_ORD
HAVING COUNT(*) > 1;
